from pbt.translations import *


ts = TranslationSet()

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='LUFS')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='RMS')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='Peak')
    .es('Pico')
    .pt('Pico')
    .fr('Crête')
    .it('Picco')
    .ja('ピーク')
    .ko('피크')
    .zhHans('峰值')
    .zhHant('峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='True\nPeak')
    .es('Pico\nVerdadero')
    .pt('Pico\nVerdadeiro')
    .fr('Crête\nRéelle')
    .it('Vero\nPicco')
    .ja('トゥルー\nピーク')
    .ko('트루\n피크')
    .zhHans('真实\n峰值')
    .zhHant('真實\n峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeasurementWindow",
    text='Momentary')
    .es('Momentáneo')
    .pt('Momentâneo')
    .fr('Momentané')
    .it('Momentaneo')
    .ja('瞬間的')
    .ko('순간')
    .zhHans('瞬间')
    .zhHant('瞬間')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeasurementWindow",
    text='Short Term')
    .es('Corto Plazo')
    .pt('Curto Prazo')
    .fr('Court Terme')
    .it('Breve Termine')
    .ja('短期的')
    .ko('단기')
    .zhHans('短期')
    .zhHant('短期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeasurementWindow",
    text='Long Term')
    .es('Largo Plazo')
    .pt('Longo Prazo')
    .fr('Long Terme')
    .it('Lungo Termine')
    .ja('長期的')
    .ko('장기')
    .zhHans('长期')
    .zhHant('長期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nPeak')
    .es('Pico\nMáximo')
    .pt('Pico\nMáximo')
    .fr('Crête\nMaximale')
    .it('Picco\nMassimo')
    .ja('ピーク\n最大値')
    .ko('최대\n피크')
    .zhHans('最大\n峰值')
    .zhHant('最大\n峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nTrue Peak')
    .es('Pico Verdadero\nMáximo')
    .pt('Pico Verdadeiro\nMáximo')
    .fr('Crête Réelle\nMaximale')
    .it('Vero Picco\nMassimo')
    .ja('トゥルーピーク\n最大値')
    .ko('최대\n트루피크')
    .zhHans('最大\n真实峰值')
    .zhHant('最大\n真實峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nMomentary')
    .es('Momentáneo\nMáximo')
    .pt('Momentâneo\nMáximo')
    .fr('Maximum\nMomentané')
    .it('Massimo\nMomentaneo')
    .ja('瞬間的\n最大値')
    .ko('순간\n최대치')
    .zhHans('最大\n瞬间')
    .zhHant('最大\n瞬間')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nShort Term')
    .es('Corto Plazo\nMáximo')
    .pt('Curto Prazo\nMáximo')
    .fr('Maximum\nCourt Terme')
    .it('Massimo\nBreve Termine')
    .ja('短期的\n最大値')
    .ko('단기\n최대치')
    .zhHans('最大\n短期')
    .zhHant('最大\n短期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Loudness\nRange')
    .es('Rango de\nVolumen')
    .pt('Variação\nde Loudness')
    .fr('Plage\nDynamique')
    .it('Intervallo\nVolume')
    .ja('ラウドネス\nレンジ')
    .ko('음량\n범위')
    .zhHans('响度\n范围')
    .zhHant('響度\n範圍')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="BalanceMeasurementWindow",
    text='ST')
    .es('CP')
    .pt('CP')
    .fr('CT')
    .it('BT')
    .ja('短期')
    .ko('단기')
    .zhHans('短期')
    .zhHant('短期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="BalanceMeasurementWindow",
    text='LT')
    .es('LP')
    .pt('LP')
    .fr(1)
    .it(1)
    .ja('長期')
    .ko('장기')
    .zhHans('长期')
    .zhHant('長期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="LoudnessMeteringUnits",
    text='Absolute')
    .es('Absoluto')
    .pt('Absoluto')
    .fr('Absolues')
    .it('Assoluto')
    .ja('絶対的')
    .ko('절대적')
    .zhHans('绝对的')
    .zhHant('絕對的')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="LoudnessMeteringUnits",
    text='Relative')
    .es('Relativo')
    .pt('Relativo')
    .fr('Relatives')
    .it('Relativo')
    .ja('相対的')
    .ko('상대적')
    .zhHans('相对的')
    .zhHant('相對的')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Channel')
    .es('Canal')
    .pt('Canal')
    .fr('Canal')
    .it('Canale')
    .ja('チャンネル')
    .ko('채널')
    .zhHans('声道')
    .zhHant('声道')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Summary')
    .es('Resumen')
    .pt('Resumo')
    .fr('Résumé')
    .it('Riassunto')
    .ja('概要')
    .ko('요약')
    .zhHans('概括')
    .zhHant('概括')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Options')
    .es('Opciones')
    .pt('Opções')
    .fr(1)
    .it('Opzioni')
    .ja('設定')
    .ko('설정')
    .zhHans('选项')
    .zhHant('選項')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Tagline",
    text='Hit the target')
    .es('Dar al blanco')
    .pt('Acerte o Alvo')
    .fr('Atteignez la cible')
    .it("Centra l'obiettivo")
    .ja('ターゲットを当てろ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='T\nA\nR\nG\nE\nT')
    .es('O\nB\nJ\nE\nT\nI\nV\nO')
    .pt('A\nL\nV\nO')
    .fr('C\nI\nB\nL\nE')
    .it('O\nB\nI\nE\nT\nT\nI\nV\nO')
    .ja('タ\nー\nゲ\nッ\nト', vertical=True)
    .ko('타\n겟')
    .zhHans('目\n标')
    .zhHant('目\n標')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='T\nR\nI\nM')
    .es('A\nJ\nU\nS\nT\nE')
    .pt('V\nO\nL\nU\nM\nE')
    .fr('V\nO\nL\nU\nM\nE')
    .it('V\nO\nL\nU\nM\nE')
    .ja('ト\nリ\nム')
    .ko('트\n림')
    .zhHans('调\n整')
    .zhHant('調\n整')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply (M)')
    .es('Aplicar (M)')
    .pt('Aplicar (M)')
    .fr('Appliquer (M)')
    .it('Applica (M)')
    .ja('適用する（瞬間）')
    .ko('적용 (순간)')
    .zhHans('应用 (瞬间)')
    .zhHant('應用 (瞬間)')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply (ST)')
    .es('Aplicar (CP)')
    .pt('Aplicar (CP)')
    .fr('Appliquer (CT)')
    .it('Applica (BT)')
    .ja('適用する（短期）')
    .ko('적용 (단기)')
    .zhHans('应用 (短期)')
    .zhHant('應用 (短期)')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply (LT)')
    .es('Aplicar (LP)')
    .pt('Aplicar (LP)')
    .fr('Appliquer (LT)')
    .it('Applica (LT)')
    .ja('適用する（長期）')
    .ko('적용 (장기)')
    .zhHans('应用 (长期)')
    .zhHant('應用 (長期)')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Fine Trim')
    .es('Ajuste Fino')
    .pt('Ajuste Fino')
    .fr('Volume Précis')
    .it('Volume Preciso')
    .ja('トリム微調整')
    .ko('미세 트림')
    .zhHans('精细调整')
    .zhHant('精細調整')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Fine Trim')
    .es('Ajuste Fino')
    .pt('Ajuste Fino')
    .fr('Volume Précis')
    .it('Volume Preciso')
    .ja('トリム微調整')
    .ko('미세 트림')
    .zhHans('精细调整')
    .zhHant('精細調整')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply Balance (ST)')
    .es('Equilibrar (CP)')
    .pt('Equilibrar (CP)')
    .fr('Équilibrer (CT)')
    .it('Bilancia (BT)')
    .ja('平準化する（短期）')
    .ko('밸런스 적용 (단기)')
    .zhHans('应用平衡 (短期)')
    .zhHant('應用平衡 (短期)')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply Balance (LT)')
    .es('Equilibrar (LP)')
    .pt('Equilibrar (LP)')
    .fr('Équilibrer (LT)')
    .it('Bilancia (LT)')
    .ja('平準化する（長期）')
    .ko('밸런스 적용 (장기)')
    .zhHans('应用平衡 (长期)')
    .zhHant('應用平衡 (長期)')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Sketch/runtime-text",
    text='Copy to Clipboard')
    .es('Copiar')
    .pt('Copiar')
    .fr('Copier dans le Presse-papier')
    .it('Copia negli appunti')
    .ja('クリップボードにコピー')
    .ko('클립보드로 복사')
    .zhHans('复制到剪贴板')
    .zhHant('複製到剪貼板')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Sketch/runtime-text",
    text='Copied!')
    .es('Copiado!')
    .pt('Copiado!')
    .fr('Copié!')
    .it('Copiato!')
    .ja('コピー完了！')
    .ko('복사 완료!')
    .zhHans('复制了！')
    .zhHant('複製了！')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Reset\nOptions')
    .es('Opciones de\nReinicio')
    .pt('Opções de\nReinicialização')
    .fr('Options de\nRéinitialisation')
    .it('Reimposta\nOpzioni')
    .ja('リセット\nの設定')
    .ko('리셋\n설정')
    .zhHans('复位\n选项')
    .zhHant('復位\n選項')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Reset on\nApply')
    .es('Reiniciar al\nAplicar')
    .pt('Reiniciar ao\nAplicar')
    .fr('Réinitialiser aprés\nApplication')
    .it('Reimposta su\nApplica')
    .ja('適用後に\nリセットする')
    .ko('적용 후\n리셋')
    .zhHans('应用后\n复位')
    .zhHant('應用後\n復位')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Reset on\nPlayback')
    .es('Reiniciar en\nReproducción')
    .pt('Reiniciar ao\nIniciar Playback')
    .fr('Réinitialiser sur\nLecture')
    .it('Reimposta su\nRiproduzione')
    .ja('再生後に\nリセットする')
    .ko('재생 후\n리셋')
    .zhHans('播放后\n复位')
    .zhHant('播放後\n復位')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Loudness\nMetering')
    .es('Medición de\nVolumen')
    .pt('Medição de\nLoudness')
    .fr('Mesure de\nSonie')
    .it('Volume\nMisurazione')
    .ja('ラウドネス\n測定')
    .ko('음량\n측정')
    .zhHans('响度测量')
    .zhHant('響度測量')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Only on\nPlayback')
    .es('Solo durante\nReproducción')
    .pt('Apenas Durante\nPlayback')
    .fr('Seulement sur\nLecture')
    .it('Solo su\nRiproduzione')
    .ja('再生中のみ')
    .ko('재생중에만')
    .zhHans('仅在播放时')
    .zhHant('僅在播放時')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Yes')
    .es('Sí')
    .pt('Sim')
    .fr('Oui')
    .it('Sì')
    .ja('有効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='No')
    .es(1)
    .pt('Não')
    .fr('Non')
    .it(1)
    .ja('無効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Only when\nUI is open')
    .es('Solo con\nVentana Abierta')
    .pt('Apenas com\nJanela Aberta')
    .fr('Seulement sous\nFenêtre Ouverte')
    .it('Solo quando\nla UI è aperta')
    .ja('ウィンドウ\n表示中のみ')
    .ko('UI 가\n열려 있을 때만')
    .zhHans('只有在\n用户界面已打开')
    .zhHant('只有在\n用戶界面已打開')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Yes')
    .es('Sí')
    .pt('Sim')
    .fr('Oui')
    .it('Sì')
    .ja('有効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='No')
    .es(1)
    .pt('Não')
    .fr('Non')
    .it(1)
    .ja('無効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Ignore\nSilence')
    .es('Ignorar\nSilencio')
    .pt('Ignorar\nSilêncios')
    .fr('Ignorer les\nSilences')
    .it('Ignora\nSilenzio')
    .ja('無音を\n無視する')
    .ko('무음을\n무시')
    .zhHans('忽略沉默')
    .zhHant('忽略沉默')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Yes')
    .es('Sí')
    .pt('Sim')
    .fr('Oui')
    .it('Sì')
    .ja('有効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='No')
    .es(1)
    .pt('Não')
    .fr('Non')
    .it(1)
    .ja('無効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Offset')
    .es('Compensación')
    .pt('Compensação')
    .fr('Compensation')
    .it('Compensazione')
    .ja('補償')
    .ko('보상')
    .zhHans('补偿')
    .zhHant('補償')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Units')
    .es('Unidades')
    .pt('Unidades')
    .fr('Unités')
    .it('Unità')
    .ja('単位')
    .ko('단위')
    .zhHans('单位')
    .zhHant('單位')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Trim Glide\nTimes')
    .es('Tiempo de\nTransición')
    .pt('Tempo de\nDeslizamento')
    .fr('Temps de\nBalayage')
    .it('Tempo\nRaggiunto')
    .ja('トリム\nグライド')
    .ko('트림\n글라이드')
    .zhHans('调整滑移\n时间')
    .zhHant('調整滑移\n時間')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Numeric Summary')
    .es('Resumen Numérico')
    .pt('Resumo Numérico')
    .fr('Résumé Numérique')
    .it('Riepilogo Numerico')
    .ja('数値概要')
    .ko('수치 요약')
    .zhHans('数值概括')
    .zhHant('數值概括')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Momentary')
    .es('Momentáneo')
    .pt('Momentâneo')
    .fr('Momentané')
    .it('Momentaneo')
    .ja('瞬間的')
    .ko('순간')
    .zhHans('瞬间')
    .zhHant('瞬間')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Short Term')
    .es('Corto Plazo')
    .pt('Curto Prazo')
    .fr('Court Terme')
    .it('Breve Termine')
    .ja('短期的')
    .ko('단기')
    .zhHans('短期')
    .zhHant('短期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Long Term')
    .es('Largo Plazo')
    .pt('Longo Prazo')
    .fr('Long Terme')
    .it('Lungo Termine')
    .ja('長期的')
    .ko('장기')
    .zhHans('长期')
    .zhHant('長期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Unit')
    .es('Unidad')
    .pt('Unidade')
    .fr('Unité')
    .it('Unità')
    .ja('単位')
    .ko('단위')
    .zhHans('单位')
    .zhHant('單位')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='LUFS')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='RMS')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Peak')
    .es('Pico')
    .pt('Pico')
    .fr('Crête')
    .it('Picco')
    .ja('ピーク')
    .ko('피크')
    .zhHans('峰值')
    .zhHant('峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='True\nPeak')
    .es('Pico\nVerdadero')
    .pt('Pico\nVerdadeiro')
    .fr('Crête\nRéelle')
    .it('Vero\nPicco')
    .ja('トゥルー\nピーク')
    .ko('트루\n피크')
    .zhHans('真实\n峰值')
    .zhHant('真實\n峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Crest\nFactor')
    .es('Factor\nde Cresta')
    .pt('Fator\nde Crista')
    .fr('Facteur\nde Crête')
    .it('Fattore\nCresta')
    .ja('クレスト\nファクタ')
    .ko('크래스트\n팩터')
    .zhHans('波峰\n因数')
    .zhHant('波峰\n因數')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Max Momentary')
    .es('Momentáneo Máximo')
    .pt('Momentâneo Máximo')
    .fr('Maximum Momentané')
    .it('Massimo Momentaneo')
    .ja('瞬間的最大値')
    .ko('순간 최대치')
    .zhHans('瞬间最大值')
    .zhHant('瞬間最大值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Max Short Term')
    .es('Corto Plazo Máximo')
    .pt('Curto Prazo Máximo')
    .fr('Maximum Court Terme')
    .it('Massimo Breve Termine')
    .ja('短期的最大値')
    .ko('단기 최대치')
    .zhHans('短期最大值')
    .zhHant('短期最大值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Loudness Range')
    .es('Rango de Volumen')
    .pt('Variação de Loudness')
    .fr('Plage Dynamique')
    .it('Intervallo Volume')
    .ja('ラウドネスレンジ')
    .ko('음량 범위')
    .zhHans('响度范围')
    .zhHant('響度範圍')
    .ar(0)
    .he(0)
)

