from pbt.translations import *


ts = TranslationSet()

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='LUFS')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja(1)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='RMS')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja(1)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='Peak')
    .es(0)
    .pt(0)
    .fr('Crête')
    .it(0)
    .ja('ピーク')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='True\nPeak')
    .es(0)
    .pt(0)
    .fr('Crête\nRéelle')
    .it(0)
    .ja('トゥルー\nピーク')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeasurementWindow",
    text='Momentary')
    .es(0)
    .pt(0)
    .fr('Momentanée')
    .it(0)
    .ja('瞬間的')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeasurementWindow",
    text='Short Term')
    .es(0)
    .pt(0)
    .fr('Court Terme')
    .it(0)
    .ja('短期的')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeasurementWindow",
    text='Long Term')
    .es(0)
    .pt(0)
    .fr('Long Terme')
    .it(0)
    .ja('長期的')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nPeak')
    .es(0)
    .pt(0)
    .fr('Crête\nMaximale')
    .it(0)
    .ja('ピーク\n最大値')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nTrue Peak')
    .es(0)
    .pt(0)
    .fr('Crête Réelle\nMaximale')
    .it(0)
    .ja('トゥルーピーク\n最大値')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nMomentary')
    .es(0)
    .pt(0)
    .fr('Momentanée\nMaximale')
    .it(0)
    .ja('瞬間的\n最大値')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nShort Term')
    .es(0)
    .pt(0)
    .fr('Court Terme\nMaximale')
    .it(0)
    .ja('短期的\n最大値')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Loudness\nRange')
    .es(0)
    .pt(0)
    .fr('Plage\nDynamique')
    .it(0)
    .ja('ラウドネス\nレンジ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="BalanceMeasurementWindow",
    text='ST')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('短期')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="BalanceMeasurementWindow",
    text='LT')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('長期')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="LoudnessMeteringUnits",
    text='Absolute')
    .es(0)
    .pt(0)
    .fr('Absolues')
    .it(0)
    .ja('絶対的')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="LoudnessMeteringUnits",
    text='Relative')
    .es(0)
    .pt(0)
    .fr('Relatives')
    .it(0)
    .ja('相対的')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Channel')
    .es(0)
    .pt(0)
    .fr('Canal')
    .it(0)
    .ja('チャンネル')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Summary')
    .es(0)
    .pt(0)
    .fr('Résumé')
    .it(0)
    .ja('概要')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Options')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('設定')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Tagline",
    text='Hit the target')
    .es(0)
    .pt(0)
    .fr('Atteignez la cible')
    .it(0)
    .ja('ターゲットを当てろ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='T\nA\nR\nG\nE\nT')
    .es(0)
    .pt(0)
    .fr('C\nI\nB\nL\nE')
    .it(0)
    .ja('タ\n｜\nゲ\nッ\nト')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='T\nR\nI\nM')
    .es(0)
    .pt(0)
    .fr('V\nO\nL\nU\nM\nE')
    .it(0)
    .ja('ト\nリ\nム')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply (M)')
    .es(0)
    .pt(0)
    .fr('Appliquer (M)')
    .it(0)
    .ja('適用する（瞬間）')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply (ST)')
    .es(0)
    .pt(0)
    .fr('Appliquer (ST)')
    .it(0)
    .ja('適用する（短期）')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply (LT)')
    .es(0)
    .pt(0)
    .fr('Appliquer (LT)')
    .it(0)
    .ja('適用する（長期）')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Fine Trim')
    .es(0)
    .pt(0)
    .fr('Volume Précis')
    .it(0)
    .ja('トリム微調整')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Fine Trim')
    .es(0)
    .pt(0)
    .fr('Volume Précis')
    .it(0)
    .ja('トリム微調整')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply Balance (ST)')
    .es(0)
    .pt(0)
    .fr('Équilibrer (ST)')
    .it(0)
    .ja('平準化する（短期）')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply Balance (LT)')
    .es(0)
    .pt(0)
    .fr('Équilibrer (LT)')
    .it(0)
    .ja('平準化する（長期）')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Reset\nOptions')
    .es(0)
    .pt(0)
    .fr('Options de\nRéinitialisation')
    .it(0)
    .ja('リセット\nの設定')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Reset on\nApply')
    .es(0)
    .pt(0)
    .fr('Réinitialiser aprés\nApplication')
    .it(0)
    .ja('適用後に\nリセットする')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Reset on\nPlayback')
    .es(0)
    .pt(0)
    .fr('Réinitialiser sur\nLecture')
    .it(0)
    .ja('再生後に\nリセットする')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Loudness\nMetering')
    .es(0)
    .pt(0)
    .fr('Mesure de\nSonie')
    .it(0)
    .ja('ラウドネス\n測定')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Only on\nPlayback')
    .es(0)
    .pt(0)
    .fr('Seulement sur\nLecture')
    .it(0)
    .ja('再生中のみ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Yes')
    .es(0)
    .pt(0)
    .fr('Oui')
    .it(0)
    .ja('有効')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='No')
    .es(0)
    .pt(0)
    .fr('Non')
    .it(0)
    .ja('無効')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Only when\nUI is open')
    .es(0)
    .pt(0)
    .fr('Seulement sous\nFenêtre Ouverte')
    .it(0)
    .ja('ウィンドウ\n表示中のみ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Yes')
    .es(0)
    .pt(0)
    .fr('Oui')
    .it(0)
    .ja('有効')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='No')
    .es(0)
    .pt(0)
    .fr('Non')
    .it(0)
    .ja('無効')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Ignore\nSilence')
    .es(0)
    .pt(0)
    .fr('Ignorer les\nSilences')
    .it(0)
    .ja('無音を\n無視する')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Yes')
    .es(0)
    .pt(0)
    .fr('Oui')
    .it(0)
    .ja('有効')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='No')
    .es(0)
    .pt(0)
    .fr('Non')
    .it(0)
    .ja('無効')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Offset')
    .es(0)
    .pt(0)
    .fr('Compensation')
    .it(0)
    .ja('補償')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Units')
    .es(0)
    .pt(0)
    .fr('Unités')
    .it(0)
    .ja('単位')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Trim Glide\nTimes')
    .es(0)
    .pt(0)
    .fr('Temps de Balayage\ndu Volume')
    .it(0)
    .ja('トリム\nグライド')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Numeric Summary')
    .es(0)
    .pt(0)
    .fr('Résumé Numérique')
    .it(0)
    .ja('数値概要')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Momentary')
    .es(0)
    .pt(0)
    .fr('Momentanée')
    .it(0)
    .ja('瞬間的')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Short Term')
    .es(0)
    .pt(0)
    .fr('Court Terme')
    .it(0)
    .ja('短期的')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Long Term')
    .es(0)
    .pt(0)
    .fr('Long Terme')
    .it(0)
    .ja('長期的')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Unit')
    .es(0)
    .pt(0)
    .fr('Unité')
    .it(0)
    .ja('単位')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='LUFS')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja(1)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='RMS')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja(1)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Peak')
    .es(0)
    .pt(0)
    .fr('Crête')
    .it(0)
    .ja('ピーク')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='True\nPeak')
    .es(0)
    .pt(0)
    .fr('Crête\nRéelle')
    .it(0)
    .ja('トゥルー\nピーク')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Crest\nFactor')
    .es(0)
    .pt(0)
    .fr('Facteur\nde Crête')
    .it(0)
    .ja('クレスト\nファクタ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Max Momentary')
    .es(0)
    .pt(0)
    .fr('Momentanée Maximale')
    .it(0)
    .ja('瞬間的最大値')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Max Short Term')
    .es(0)
    .pt(0)
    .fr('Court Terme Maximale')
    .it(0)
    .ja('短期的最大値')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Loudness Range')
    .es(0)
    .pt(0)
    .fr('Plage Dynamique')
    .it(0)
    .ja('ラウドネスレンジ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

