from pbt.translations import *


ts = TranslationSet()

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='LUFS')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='RMS')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='Peak')
    .es(0)
    .pt(0)
    .fr('Crête')
    .it(0)
    .ja('ピーク')
    .ko('피크')
    .zhHans('峰值')
    .zhHant('峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterType",
    text='True\nPeak')
    .es(0)
    .pt(0)
    .fr('Crête\nRéelle')
    .it(0)
    .ja('トゥルー\nピーク')
    .ko('트루\n피크')
    .zhHans('真实\n峰值')
    .zhHant('真實\n峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeasurementWindow",
    text='Momentary')
    .es(0)
    .pt(0)
    .fr('Momentanée')
    .it(0)
    .ja('瞬間的')
    .ko('순간')
    .zhHans('瞬间')
    .zhHant('瞬間')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeasurementWindow",
    text='Short Term')
    .es(0)
    .pt(0)
    .fr('Court Terme')
    .it(0)
    .ja('短期的')
    .ko('단기')
    .zhHans('短期')
    .zhHant('短期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeasurementWindow",
    text='Long Term')
    .es(0)
    .pt(0)
    .fr('Long Terme')
    .it(0)
    .ja('長期的')
    .ko('장기')
    .zhHans('长期')
    .zhHant('長期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nPeak')
    .es(0)
    .pt(0)
    .fr('Crête\nMaximale')
    .it(0)
    .ja('ピーク\n最大値')
    .ko('최대\n피크')
    .zhHans('最大\n峰值')
    .zhHant('最大\n峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nTrue Peak')
    .es(0)
    .pt(0)
    .fr('Crête Réelle\nMaximale')
    .it(0)
    .ja('トゥルーピーク\n最大値')
    .ko('최대\n트루피크')
    .zhHans('最大\n真实峰值')
    .zhHant('最大\n真實峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nMomentary')
    .es(0)
    .pt(0)
    .fr('Momentanée\nMaximale')
    .it(0)
    .ja('瞬間的\n最大値')
    .ko('순간\n최대치')
    .zhHans('最大\n瞬间')
    .zhHant('最大\n瞬間')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Max\nShort Term')
    .es(0)
    .pt(0)
    .fr('Court Terme\nMaximale')
    .it(0)
    .ja('短期的\n最大値')
    .ko('단기\n최대치')
    .zhHans('最大\n短期')
    .zhHant('最大\n短期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="MeterMode",
    text='Loudness\nRange')
    .es(0)
    .pt(0)
    .fr('Plage\nDynamique')
    .it(0)
    .ja('ラウドネス\nレンジ')
    .ko('음량\n범위')
    .zhHans('响度\n范围')
    .zhHant('響度\n範圍')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="BalanceMeasurementWindow",
    text='ST')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('短期')
    .ko('단기')
    .zhHans('短期')
    .zhHant('短期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="BalanceMeasurementWindow",
    text='LT')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('長期')
    .ko('장기')
    .zhHans('长期')
    .zhHant('長期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="LoudnessMeteringUnits",
    text='Absolute')
    .es(0)
    .pt(0)
    .fr('Absolues')
    .it(0)
    .ja('絶対的')
    .ko('절대적')
    .zhHans('绝对的')
    .zhHant('絕對的')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="LoudnessMeteringUnits",
    text='Relative')
    .es(0)
    .pt(0)
    .fr('Relatives')
    .it(0)
    .ja('相対的')
    .ko('상대적')
    .zhHans('相对的')
    .zhHant('相對的')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Channel')
    .es(0)
    .pt(0)
    .fr('Canal')
    .it(0)
    .ja('チャンネル')
    .ko('채널')
    .zhHans('声道')
    .zhHant('声道')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Summary')
    .es(0)
    .pt(0)
    .fr('Résumé')
    .it(0)
    .ja('概要')
    .ko('요약')
    .zhHans('概括')
    .zhHant('概括')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Options')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('設定')
    .ko('설정')
    .zhHans('选项')
    .zhHant('選項')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Tagline",
    text='Hit the target')
    .es(0)
    .pt(0)
    .fr('Atteignez la cible')
    .it(0)
    .ja('ターゲットを当てろ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='T\nA\nR\nG\nE\nT')
    .es(0)
    .pt(0)
    .fr('C\nI\nB\nL\nE')
    .it(0)
    .ja('タ\nー\nゲ\nッ\nト', vertical=True)
    .ko('타\n겟')
    .zhHans('目\n标')
    .zhHant('目\n標')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='T\nR\nI\nM')
    .es(0)
    .pt(0)
    .fr('V\nO\nL\nU\nM\nE')
    .it(0)
    .ja('ト\nリ\nム')
    .ko('트\n림')
    .zhHans('调\n整')
    .zhHant('調\n整')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply (M)')
    .es(0)
    .pt(0)
    .fr('Appliquer (M)')
    .it(0)
    .ja('適用する（瞬間）')
    .ko('적용 (순간)')
    .zhHans('应用 (瞬间)')
    .zhHant('應用 (瞬間)')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply (ST)')
    .es(0)
    .pt(0)
    .fr('Appliquer (ST)')
    .it(0)
    .ja('適用する（短期）')
    .ko('적용 (단기)')
    .zhHans('应用 (短期)')
    .zhHant('應用 (短期)')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply (LT)')
    .es(0)
    .pt(0)
    .fr('Appliquer (LT)')
    .it(0)
    .ja('適用する（長期）')
    .ko('적용 (장기)')
    .zhHans('应用 (长期)')
    .zhHant('應用 (長期)')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Fine Trim')
    .es(0)
    .pt(0)
    .fr('Volume Précis')
    .it(0)
    .ja('トリム微調整')
    .ko('미세 트림')
    .zhHans('精细调整')
    .zhHant('精細調整')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Fine Trim')
    .es(0)
    .pt(0)
    .fr('Volume Précis')
    .it(0)
    .ja('トリム微調整')
    .ko('미세 트림')
    .zhHans('精细调整')
    .zhHant('精細調整')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply Balance (ST)')
    .es(0)
    .pt(0)
    .fr('Équilibrer (ST)')
    .it(0)
    .ja('平準化する（短期）')
    .ko('밸런스 적용 (단기)')
    .zhHans('应用平衡 (短期)')
    .zhHant('應用平衡 (短期)')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Apply Balance (LT)')
    .es(0)
    .pt(0)
    .fr('Équilibrer (LT)')
    .it(0)
    .ja('平準化する（長期）')
    .ko('밸런스 적용 (장기)')
    .zhHans('应用平衡 (长期)')
    .zhHant('應用平衡 (長期)')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Reset\nOptions')
    .es(0)
    .pt(0)
    .fr('Options de\nRéinitialisation')
    .it(0)
    .ja('リセット\nの設定')
    .ko('리셋\n설정')
    .zhHans('复位\n选项')
    .zhHant('復位\n選項')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Reset on\nApply')
    .es(0)
    .pt(0)
    .fr('Réinitialiser aprés\nApplication')
    .it(0)
    .ja('適用後に\nリセットする')
    .ko('적용 후\n 리셋')
    .zhHans('应用后\n 复位')
    .zhHant('應用後\n 復位')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Reset on\nPlayback')
    .es(0)
    .pt(0)
    .fr('Réinitialiser sur\nLecture')
    .it(0)
    .ja('再生後に\nリセットする')
    .ko('재생 후\n 리셋')
    .zhHans('播放后\n 复位')
    .zhHant('播放後\n 復位')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Loudness\nMetering')
    .es(0)
    .pt(0)
    .fr('Mesure de\nSonie')
    .it(0)
    .ja('ラウドネス\n測定')
    .ko('음량\n측정')
    .zhHans('响度测量')
    .zhHant('響度測量')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Only on\nPlayback')
    .es(0)
    .pt(0)
    .fr('Seulement sur\nLecture')
    .it(0)
    .ja('再生中のみ')
    .ko('재생중에만')
    .zhHans('仅在播放时')
    .zhHant('僅在播放時')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Yes')
    .es(0)
    .pt(0)
    .fr('Oui')
    .it(0)
    .ja('有効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='No')
    .es(0)
    .pt(0)
    .fr('Non')
    .it(0)
    .ja('無効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Only when\nUI is open')
    .es(0)
    .pt(0)
    .fr('Seulement sous\nFenêtre Ouverte')
    .it(0)
    .ja('ウィンドウ\n表示中のみ')
    .ko('UI가\n열려 있을 때만')
    .zhHans('只有在\n用户界面已打开')
    .zhHant('只有在\n用戶界面已打開')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Yes')
    .es(0)
    .pt(0)
    .fr('Oui')
    .it(0)
    .ja('有効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='No')
    .es(0)
    .pt(0)
    .fr('Non')
    .it(0)
    .ja('無効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Ignore\nSilence')
    .es(0)
    .pt(0)
    .fr('Ignorer les\nSilences')
    .it(0)
    .ja('無音を\n無視する')
    .ko('무음을\n무시')
    .zhHans('忽略沉默')
    .zhHant('忽略沉默')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Yes')
    .es(0)
    .pt(0)
    .fr('Oui')
    .it(0)
    .ja('有効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='No')
    .es(0)
    .pt(0)
    .fr('Non')
    .it(0)
    .ja('無効')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Offset')
    .es(0)
    .pt(0)
    .fr('Compensation')
    .it(0)
    .ja('補償')
    .ko('보상')
    .zhHans('补偿')
    .zhHant('補償')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Units')
    .es(0)
    .pt(0)
    .fr('Unités')
    .it(0)
    .ja('単位')
    .ko('단위')
    .zhHans('单位')
    .zhHant('單位')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Trim Glide\nTimes')
    .es(0)
    .pt(0)
    .fr('Temps de Balayage\ndu Volume')
    .it(0)
    .ja('トリム\nグライド')
    .ko('트림\n글라이드')
    .zhHans('调整滑移\n时间')
    .zhHant('調整滑移\n時間')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Numeric Summary')
    .es(0)
    .pt(0)
    .fr('Résumé Numérique')
    .it(0)
    .ja('数値概要')
    .ko('수치 요약')
    .zhHans('数值概括')
    .zhHant('數值概括')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Momentary')
    .es(0)
    .pt(0)
    .fr('Momentanée')
    .it(0)
    .ja('瞬間的')
    .ko('순간')
    .zhHans('瞬间')
    .zhHant('瞬間')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Short Term')
    .es(0)
    .pt(0)
    .fr('Court Terme')
    .it(0)
    .ja('短期的')
    .ko('단기')
    .zhHans('短期')
    .zhHant('短期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Long Term')
    .es(0)
    .pt(0)
    .fr('Long Terme')
    .it(0)
    .ja('長期的')
    .ko('장기')
    .zhHans('长期')
    .zhHant('長期')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Unit')
    .es(0)
    .pt(0)
    .fr('Unité')
    .it(0)
    .ja('単位')
    .ko('단위')
    .zhHans('单位')
    .zhHant('單位')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='LUFS')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='RMS')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Peak')
    .es(0)
    .pt(0)
    .fr('Crête')
    .it(0)
    .ja('ピーク')
    .ko('피크')
    .zhHans('峰值')
    .zhHant('峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='True\nPeak')
    .es(0)
    .pt(0)
    .fr('Crête\nRéelle')
    .it(0)
    .ja('トゥルー\nピーク')
    .ko('트루\n피크')
    .zhHans('真实\n峰值')
    .zhHant('真實\n峰值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Crest\nFactor')
    .es(0)
    .pt(0)
    .fr('Facteur\nde Crête')
    .it(0)
    .ja('クレスト\nファクタ')
    .ko('크래스트\n팩터')
    .zhHans('波峰\n因数')
    .zhHant('波峰\n因數')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Max Momentary')
    .es(0)
    .pt(0)
    .fr('Momentanée Maximale')
    .it(0)
    .ja('瞬間的最大値')
    .ko('순간 최대치')
    .zhHans('瞬间最大值')
    .zhHant('瞬間最大值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Max Short Term')
    .es(0)
    .pt(0)
    .fr('Court Terme Maximale')
    .it(0)
    .ja('短期的最大値')
    .ko('단기 최대치')
    .zhHans('短期最大值')
    .zhHant('短期最大值')
    .ar(0)
    .he(0)
)

ts.append(T(tag="SketchLabel/text",
    text='Loudness Range')
    .es(0)
    .pt(0)
    .fr('Plage Dynamique')
    .it(0)
    .ja('ラウドネスレンジ')
    .ko('음량 범위')
    .zhHans('响度范围')
    .zhHant('響度範圍')
    .ar(0)
    .he(0)
)

