from pbt.translations import *


ts = TranslationSet()

ts.append(T(tag="ClumpLabel/text",
    text='LINK')
    .es('ENLACE')
    .pt(1)
    .fr('COUPLAGE')
    .ja('リンク')
    .ko('링크 설정')
    .zhHans('连结')
    .zhHant('連結')
    .ar('الوصل')
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='OUT')
    .es('SALIDA')
    .pt('SAÍDA')
    .fr('SORTIE')
    .ja('アウト')
    .ko('아웃풋')
    .zhHans('输出')
    .zhHant('輸出')
    .ar(' الخرج')
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='RATIO')
    .es('PROPORCIÓN')
    .pt('PROPORÇÃO')
    .fr(1)
    .ja('比率')
    .ko('비율')
    .zhHans('比率')
    .zhHant('比率')
    .ar('نسبة الضغط')
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='SIDECHAIN')
    .es(1)
    .pt(1)
    .fr(1)
    .ja('サイドチェイン')
    .ko('사이드체인')
    .zhHans('旁链')
    .zhHant('旁鏈')
    .ar(' السايدشين')
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='SPEED')
    .es('VELOCIDAD')
    .pt('VELOCIDADE')
    .fr('VITESSE')
    .ja('スピード')
    .ko('속도')
    .zhHans('速度')
    .zhHant('速度')
    .ar('السرعة')
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='THRESH')
    .es('LÍMITE')
    .pt('LIMITE')
    .fr('SEUIL')
    .ja('スレッショルド')
    .ko('기준 레벨')
    .zhHans('阈')
    .zhHant('閾')
    .ar('حد العتبة')
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='VIBE')
    .es('VIBRA')
    .pt(1)
    .fr('AMBIANCE')
    .ja('バイブ')
    .ko('톤 조정')
    .zhHans('氛围')
    .zhHant('氛圍')
    .ar('الجو')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Attack')
    .es('Ataque')
    .pt('Ataque')
    .fr('Attaque')
    .ja('アタック')
    .ko('어택 타임')
    .zhHans('起动时间')
    .zhHant('起動時間')
    .ar('زمن التطبيق')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Auto Gain')
    .es('Ganancia auto.')
    .pt('Ganho Autom.')
    .fr('Gain Auto')
    .ja('オートゲイン')
    .ko('오토 게인 설정')
    .zhHans('自动增益')
    .zhHant('自動增益')
    .ar('الربح التلقائي')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Color')
    .es('Coloración')
    .pt('Coloração')
    .fr('Coloration')
    .ja('カラー')
    .ko('컬러')
    .zhHans('色彩')
    .zhHant('色彩')
    .ar('اللون')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='DRY')
    .es(1)
    .pt(1)
    .fr(1)
    .ja('原音')
    .ko('원음')
    .zhHans('干声')
    .zhHant('乾聲')
    .ar('جاف')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='FRDY')
    .es(1)
    .pt(1)
    .fr(1)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(1)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Link\nAmount')
    .es('Intensidad\nde enlace')
    .pt('Intensidade\ndo Link')
    .fr('Intensité\ndu Couplage')
    .ja('リンクパーセンテージ')
    .ko('링크 정도')
    .zhHans('连结程度')
    .zhHant('連結程度')
    .ar('كمية\nالوصل')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Link\nSide Gain')
    .es('Ganancia de\nenlace de Side')
    .pt('Ganho\nSide')
    .fr('Gain de Side\ndu Couplage')
    .ja('リンクサイドゲイン')
    .ko('링크 사이드 게인')
    .zhHans('连结侧信号增益')
    .zhHant('連結側信號增益')
    .ar('وصل الربح \nالجانبي')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Link Mode')
    .es('Modo de enlace')
    .pt('Modo do Link')
    .fr('Mode de Couplage')
    .ja('リンクモード')
    .ko('링크 모드')
    .zhHans('连结模式')
    .zhHant('連結模式')
    .ar('وضعُ الوصل ')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Release')
    .es('Relajación')
    .pt('Repouso')
    .fr('Retour')
    .ja('リリース')
    .ko('릴리즈 타임')
    .zhHans('释放时间')
    .zhHant('釋放時間')
    .ar('التحرير ')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Sidechain\nHPF')
    .es('Filtro pasa altos\nde Sidechain')
    .pt('Filtro Passa-Altas\ndo Sidechain')
    .fr('Passe-Haut\ndu Sidechain')
    .ja('サイドチェインHPF')
    .ko('사이드체인 HPF')
    .zhHans('旁链高通滤波器')
    .zhHant('旁鏈高通濾波器')
    .ar('مرشح الترددا\n العالية للسايدشين')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Sidechain\nTrim')
    .es('Ajuste\nde Sidechain')
    .pt('Sidechain\nVolume')
    .fr('Volume\ndu Sidechain')
    .ja('サイドチェイントリム')
    .ko('사이드체인 트림')
    .zhHans('旁链修剪')
    .zhHant('旁鏈修剪')
    .ar('مُوازَنةٌ\nالسايدشين')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Sidechain Source')
    .es('Fuente de Sidechain')
    .pt('Sidechain – Fonte')
    .fr('Source de Couplage')
    .ja('サイドチェインソース')
    .ko('사이드체인 소스 선택')
    .zhHans('旁链声源')
    .zhHant('旁鏈聲源')
    .ar('منبع السايدشين')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Warmth')
    .es('Calidez')
    .pt('Calor')
    .fr('Chaleur')
    .ja('ウォーム')
    .ko('따스함')
    .zhHans('暖度')
    .zhHant('暖度')
    .ar('الدفء')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="LinkMode",
    text='Left/Right')
    .es('Izquierdo/Derecho')
    .pt('Esquerda/Direita')
    .fr('Gauche/Droite')
    .ja('左/右')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('يمين/يسار')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="LinkMode",
    text='Mid/Side')
    .es(1)
    .pt('Meio/Lados')
    .fr(1)
    .ja('ミッド/サイド')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('ميد/سايد')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="SidechainSource",
    text='External')
    .es('Externa')
    .pt('Externa')
    .fr('Externe')
    .ja('外部')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('خارجي')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="SidechainSource",
    text='Internal')
    .es('Interna')
    .pt('Interna')
    .fr('Interne')
    .ja('内部')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('داخلي')
    .he(0)
)

ts.append(T(tag="Tagline",
    text='Peak limiter w/ a big magnetic field.')
    .es('Limitador de picos con un gran campo magnético.')
    .pt('Limitador de picos com um campo magnético gigante.')
    .fr('Limiteur de crête avec un grand champ magnétique.')
    .ja('マルチカラーのバイブス\u3000音楽の為のピークリミッター')
    .ko('거대한 자기장 같은 피크 리미터')
    .zhHans('带有强大磁场的峰值限制器')
    .zhHant('帶有強大磁場的峰值限制器')
    .ar('محدِّد قِمم مع حقل مغناطيسي كبير')
    .he(0)
)

