from pbtranslations.translations import *


ts = TranslationSet()

ts.append(T(tag="Tagline",
    text='The soft clip from VCME')
    .es(0)
    .pt('O clipping suave do VCME')
    .fr('Le soft clip de VCME')
    .it(0)
    .ja('VCMEのソフトクリップ')
    .ko('VCME의 소프트 클립')
    .zhHans('VCME的軟削峰')
    .zhHant('VCME的軟削峰')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipReadout",
    text='LMTR GR')
    .es(0)
    .pt('LMTR RG')
    .fr(1)
    .it(0)
    .ja('リミターGR')
    .ko('리미터 GR')
    .zhHans('限幅GR')
    .zhHant('限幅GR')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipReadout",
    text='LUFS (LT)')
    .es('LUFS (LP)')
    .pt('LUFS (LP)')
    .fr('LUFS (LT)')
    .it('LUFS (LT)')
    .ja('LUFS (長期)')
    .ko('LUFS (장기)')
    .zhHans('LUFS (长期)')
    .zhHant('LUFS (長期)')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipReadout",
    text='LRA')
    .es(0)
    .pt(1)
    .fr(1)
    .it(0)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterBrickwall",
    text='Follows Mix')
    .es(0)
    .pt('Seguir Mix')
    .fr('Suivre Mix')
    .it(0)
    .ja('ミックスに従う')
    .ko('믹스 연동')
    .zhHans('混音联动')
    .zhHant('混音聯動')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterBrickwall",
    text='Brickwall')
    .es(0)
    .pt(1)
    .fr(1)
    .it(0)
    .ja('ブリックウォール')
    .ko('브릭월')
    .zhHans('砖墙限幅')
    .zhHant('磚牆限幅')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipGainComp",
    text='Auto')
    .es('Automático')
    .pt('Automático')
    .fr('Automatique')
    .it('Automatico')
    .ja('自動')
    .ko('자동')
    .zhHans('自动')
    .zhHant('自動')
    .ar('تلقائي')
)

ts.append(T(tag="Parameter/option",
    context="SoftClipGainComp",
    text='Manual')
    .es(1)
    .pt(1)
    .fr('Manuel')
    .it('Manuale')
    .ja('手動')
    .ko('수동')
    .zhHans('手动')
    .zhHant('手動')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="EmphasisSource",
    text='internal')
    .es('interna')
    .pt('interna')
    .fr('interne')
    .it('interna')
    .ja('内部')
    .ko('인터널')
    .zhHans('内部')
    .zhHant('內部')
    .ar('داخلي')
)

ts.append(T(tag="Parameter/option",
    context="EmphasisSource",
    text='external')
    .es('externa')
    .pt('externa')
    .fr('externe')
    .it('esterna')
    .ja('外部')
    .ko('엑스터널')
    .zhHans('外部')
    .zhHant('外部')
    .ar('خارجي')
)

ts.append(T(tag="Parameter/option",
    context="CompLinkMode",
    text='Left/Right')
    .es('Izquierda/Derecha')
    .pt('Esquerda/Direita')
    .fr('Gauche/Droite')
    .it('Sinistra/Destra')
    .ja('左/右')
    .ko('좌/우')
    .zhHans('左/右')
    .zhHant('左/右')
    .ar('يمين/يسار')
)

ts.append(T(tag="Parameter/option",
    context="CompLinkMode",
    text='Mid/Side')
    .es(1)
    .pt('Meio/Lados')
    .fr(1)
    .it('Centro/Lati')
    .ja('ミッド/サイド')
    .ko('미드/사이드')
    .zhHans('中/侧')
    .zhHant('中/側')
    .ar('ميد/سايد')
)

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterLink",
    text='Off')
    .es(1)
    .pt('Des.')
    .fr(1)
    .it(1)
    .ja('オフ')
    .ko('오프')
    .zhHans('关')
    .zhHant('關')
    .ar(1)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterLink",
    text='Hybrid')
    .es(0)
    .pt('Híbrido')
    .fr('Hybride')
    .it(0)
    .ja('ハイブリッド')
    .ko('하이브리드')
    .zhHans('混合')
    .zhHant('混合')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterLink",
    text='Full')
    .es(0)
    .pt('Total')
    .fr('Complet')
    .it(0)
    .ja('フル')
    .ko('풀')
    .zhHans('全开')
    .zhHant('全開')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Emphasis')
    .es('Énfasis')
    .pt('Ênfase')
    .fr('Accent.')
    .it('Enfasi')
    .ja('エンファシス')
    .ko('엠퍼시스')
    .zhHans('强调')
    .zhHant('強調')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Linking')
    .es('Vínculo')
    .pt('Vínculo')
    .fr('Couplage')
    .it('Accoppiamento')
    .ja('リンク')
    .ko('링크 설정')
    .zhHans('连结')
    .zhHant('連結')
    .ar('الوصل')
)

ts.append(T(tag="Parameter/option",
    text='saturation')
    .es('saturación')
    .pt('saturação')
    .fr(1)
    .it('saturazione')
    .ja('サチュレーション')
    .ko('새츄레이션')
    .zhHans('饱和')
    .zhHant('飽和')
    .ar('التشبع')
)

ts.append(T(tag="ClumpLabel/text",
    text='slew')
    .es(0)
    .pt(0)
    .fr('balayage')
    .it(0)
    .ja('スルー')
    .ko('슬루')
    .zhHans('斜率')
    .zhHant('斜率')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    text='limiter')
    .es(0)
    .pt(1)
    .fr('limiteur')
    .it(0)
    .ja('リミター')
    .ko('리미터')
    .zhHans('限幅器')
    .zhHant('限幅器')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='slew')
    .es(0)
    .pt(0)
    .fr('balayage')
    .it(0)
    .ja('スルー')
    .ko('슬루')
    .zhHans('斜率')
    .zhHant('斜率')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='in')
    .es('entrada')
    .pt('entrada')
    .fr('entrée')
    .it('ingr')
    .ja('イン')
    .ko('인풋')
    .zhHans('输入')
    .zhHant('輸入')
    .ar('دَخْل')
)

ts.append(T(tag="ClumpLabel/text",
    text='drive')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('ドライブ')
    .ko('드라이브')
    .zhHans('驱动')
    .zhHant('驅動')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='mix')
    .es('mezcla')
    .pt(1)
    .fr(1)
    .it('miscela')
    .ja('ミックス')
    .ko('믹스')
    .zhHans('混合')
    .zhHant('混合')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='out')
    .es('salida')
    .pt('saída')
    .fr('sortie')
    .it('uscita')
    .ja('アウト')
    .ko('아웃풋')
    .zhHans('输出')
    .zhHant('輸出')
    .ar('خَرْج')
)

ts.append(T(tag="ParamLabel/text",
    text='tilt')
    .es('incl')
    .pt('incl')
    .fr('incl')
    .it('pend')
    .ja('チルト')
    .ko('틸트')
    .zhHans('倾斜')
    .zhHant('傾斜')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='trim')
    .es('ajuste')
    .pt('volume')
    .fr('volume')
    .it('vol')
    .ja('トリム')
    .ko('트림')
    .zhHans('调整')
    .zhHant('調整')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='source')
    .es('fuente')
    .pt('fonte')
    .fr(1)
    .it('sorgente')
    .ja('音源')
    .ko('소스')
    .zhHans('声源')
    .zhHant('聲源')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='blend')
    .es('mezcla')
    .pt('mescla')
    .fr('mélange')
    .it('miscela')
    .ja('ブレンド')
    .ko('블렌드')
    .zhHans('混合')
    .zhHant('混合')
    .ar('مزج ال')
)

ts.append(T(tag="ClumpLabel/text",
    text='Soft Clip')
    .es(0)
    .pt('Clipping Suave')
    .fr(1)
    .it(0)
    .ja('ソフトクリップ')
    .ko('소프트 클립')
    .zhHans('软削峰')
    .zhHant('軟削峰')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='limiter link')
    .es(0)
    .pt('link do limiter')
    .fr('couplage du limiteur')
    .it(0)
    .ja('リミターリンク')
    .ko('리미터 링크')
    .zhHans('限幅器链接')
    .zhHant('限幅器連結')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='sat side trim')
    .es(0)
    .pt('volume de saturação dos lados')
    .fr('volume du side de saturation')
    .it(0)
    .ja('サチュレーションサイドトリム')
    .ko('새츄 사이드 트림')
    .zhHans('饱和侧声道调节')
    .zhHant('飽和側聲道調節')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='LFE')
    .es(0)
    .pt(1)
    .fr(1)
    .it(0)
    .ja('低域効果')
    .ko(1)
    .zhHans('低频效果')
    .zhHant('低頻效果')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='amount')
    .es('intensidad')
    .pt('quantidade')
    .fr('intensité')
    .it('quantità')
    .ja('量')
    .ko('정도')
    .zhHans('量')
    .zhHant('量')
    .ar('الكمية')
)

ts.append(T(tag="ParamLabel/text",
    text='trim')
    .es('ajuste')
    .pt('volume')
    .fr('volume')
    .it('vol')
    .ja('トリム')
    .ko('트림')
    .zhHans('调整')
    .zhHant('調整')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Center')
    .es(0)
    .pt('Centro')
    .fr('Centre')
    .it(0)
    .ja('センター')
    .ko('센터')
    .zhHans('中央')
    .zhHant('中央')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='amount')
    .es('intensidad')
    .pt('quantidade')
    .fr('intensité')
    .it('quantità')
    .ja('量')
    .ko('정도')
    .zhHans('量')
    .zhHant('量')
    .ar('الكمية')
)

ts.append(T(tag="ParamLabel/text",
    text='trim')
    .es('ajuste')
    .pt('volume')
    .fr('volume')
    .it('vol')
    .ja('トリム')
    .ko('트림')
    .zhHans('调整')
    .zhHant('調整')
    .ar(0)
)

