from pbt.translations import *


ts = TranslationSet()

ts.append(T(tag="Parameter/option",
    context="TempoMode",
    text='BPM Sync')
    .es('BPM Sinc')
    .pt('BPM Sinc')
    .fr(1)
    .it('BPM Sinc')
    .ja('BPMシンク')
    .ko('BPM 싱크')
    .zhHans('BPM同步')
    .zhHant('BPM同步')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="TempoMode",
    text='BPM Free')
    .es(0)
    .pt('BPM Livre')
    .fr('BPM Libre')
    .it('No Sinc')
    .ja('BPMフリー')
    .ko('BPM 프리')
    .zhHans('BPM 自由')
    .zhHant('BPM 自由')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="TempoMode",
    text='MS')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AInputMode",
    text='Left')
    .es('Izquierda')
    .pt('Esquerda')
    .fr('Gauche')
    .it('Sinistra')
    .ja('左')
    .ko('좌')
    .zhHans('左')
    .zhHant('左')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AInputMode",
    text='Right')
    .es('Derecha')
    .pt('Direita')
    .fr('Droite')
    .it('Destra')
    .ja('右')
    .ko('우')
    .zhHans('右')
    .zhHant('右')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="AInputMode",
    text='Sum')
    .es(0)
    .pt('Soma')
    .fr('Somme')
    .it('Somma')
    .ja('合計')
    .ko('합계')
    .zhHans('和')
    .zhHant('和')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="BInputMode",
    text='Right')
    .es('Derecha')
    .pt('Direita')
    .fr('Droite')
    .it('Destra')
    .ja('右')
    .ko('우')
    .zhHans('右')
    .zhHant('右')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="BInputMode",
    text='Left')
    .es('Izquierda')
    .pt('Esquerda')
    .fr('Gauche')
    .it('Sinistra')
    .ja('左')
    .ko('좌')
    .zhHans('左')
    .zhHant('左')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="BInputMode",
    text='Sum')
    .es(0)
    .pt('Soma')
    .fr('Somme')
    .it('Somma')
    .ja('合計')
    .ko('합계')
    .zhHans('和')
    .zhHant('和')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="GlideMode",
    text='Relative')
    .es('Relativo')
    .pt('Relativo')
    .fr('Relatif')
    .it('Relativo')
    .ja('相対的')
    .ko('상대적')
    .zhHans('相对的')
    .zhHant('相對的')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="GlideMode",
    text='Absolute')
    .es('Absoluto')
    .pt('Absoluto')
    .fr('Absolu')
    .it('Assoluto')
    .ja('絶対的')
    .ko('절대적')
    .zhHans('绝对的')
    .zhHant('絕對的')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="SpringDecayMode",
    text='Auto')
    .es('Automático')
    .pt('Automático')
    .fr('Automatique')
    .it('Automatico')
    .ja('自動')
    .ko('자동')
    .zhHans('自动')
    .zhHant('自動')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="SpringDecayMode",
    text='Manual')
    .es(1)
    .pt(1)
    .fr('Manuel')
    .it('Manuale')
    .ja('手動')
    .ko('수동')
    .zhHans('手动')
    .zhHant('手動')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Tagline",
    text='A weird little delay concept')
    .es(0)
    .pt('Uma concepção esquisitinha de delay')
    .fr('Un petit concept de delay hors norme')
    .it('Un piccolo, strano concetto di delay')
    .ja('少し変わったディレイコンセプト')
    .ko('조금은 이상한 딜레이 컨셉')
    .zhHans('一个奇怪的小延迟概念')
    .zhHant('一個奇怪的小延遲概念')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='SYNC')
    .es('SINC')
    .pt('SINC')
    .fr(1)
    .it('SINC')
    .ja('シンク')
    .ko('싱크')
    .zhHans('同步')
    .zhHant('同步')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Free')
    .es(0)
    .pt('Livre')
    .fr('Libre')
    .it('No Sinc')
    .ja('フリー')
    .ko('프리')
    .zhHans('自由')
    .zhHant('自由')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/bgtext",
    text='Spring')
    .es(0)
    .pt('Mola')
    .fr('Ressort')
    .it('Molla')
    .ja('スプリング', vertical=True)
    .ko('스프링')
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/bgtext",
    text='Feedback')
    .es(0)
    .pt('Retroalimentação')
    .fr(1)
    .it(1)
    .ja('フィードバック', vertical=True)
    .ko('피드백')
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/bgtext",
    text='Output')
    .es('Salida')
    .pt('Saída')
    .fr('Sortie')
    .it('Uscita')
    .ja('アウトプット', vertical=True)
    .ko('아웃풋')
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Mix')
    .es('Mezcla')
    .pt(1)
    .fr(1)
    .it('Miscela')
    .ja('ミックス')
    .ko('믹스')
    .zhHans('混合')
    .zhHant('混合')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Kill All')
    .es(0)
    .pt('Desligamento Total')
    .fr('Arrêt Complet')
    .it('Silenzia Tutti')
    .ja('全て停止')
    .ko('모두 정지')
    .zhHans('全部停止')
    .zhHant('全部停止')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Kill Feedback')
    .es(0)
    .pt('Retroalimentação')
    .fr('Arrêt Feedback')
    .it('Silenzia il FB')
    .ja('フィードバック停止')
    .ko('피드백 정지')
    .zhHans('消除反馈')
    .zhHant('消除回饋')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Infinite Hold')
    .es(0)
    .pt('Manter Infinito')
    .fr('Hold Infini')
    .it('Congela')
    .ja('無限ホールド')
    .ko('무한 홀드')
    .zhHans('无限保持')
    .zhHant('無限保持')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Spring Hold')
    .es(0)
    .pt('Manter Mola')
    .fr('Hold Ressort')
    .it('Congela Molla')
    .ja('スプリングホールド')
    .ko('스프링 홀드')
    .zhHans('弹簧保持')
    .zhHant('彈簧保持')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Tape')
    .es('Cinta')
    .pt('Fita')
    .fr(1)
    .it('Nastro')
    .ja('テープ')
    .ko('테이프')
    .zhHans('磁带')
    .zhHant('磁帶')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Lofi')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('ローファイ')
    .ko('로우파이')
    .zhHans('低保真度')
    .zhHant('低傳真度')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Wobble')
    .es(0)
    .pt('Oscilação')
    .fr('Oscill')
    .it('Instabilità')
    .ja('ぐらぐら')
    .ko('흔들흔들')
    .zhHans('摇晃')
    .zhHant('搖晃')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Filter')
    .es('Filtro')
    .pt('Filtro')
    .fr('Filtre')
    .it('Filtro')
    .ja('フィルター')
    .ko('필터')
    .zhHans('滤波')
    .zhHant('濾波')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Freq')
    .es('Frec')
    .pt(1)
    .fr('Fréq')
    .it(1)
    .ja('周波数')
    .ko('프리퀀시')
    .zhHans('频率')
    .zhHant('頻率')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Binaural')
    .es(0)
    .pt(1)
    .fr(1)
    .it('Binaurale')
    .ja('バイノーラル')
    .ko('바이노럴')
    .zhHans('双耳')
    .zhHant('雙耳')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Spread')
    .es(0)
    .pt('Difusão')
    .fr('Diffusion')
    .it('Diffusione')
    .ja('スプレッド')
    .ko('스프레드')
    .zhHans('传播')
    .zhHant('傳播')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Glide')
    .es('Barrido')
    .pt('Deslizar')
    .fr('Balayage')
    .it('Portamento')
    .ja('グライド')
    .ko('글라이드')
    .zhHans('滑移')
    .zhHant('滑移')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Time')
    .es('Tiempo')
    .pt('Tempo')
    .fr('Temps')
    .it('Tempo')
    .ja('時間')
    .ko('시간')
    .zhHans('时间')
    .zhHant('時間')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Spring')
    .es(0)
    .pt('Mola')
    .fr('Ressort')
    .it('Molla')
    .ja('スプリング')
    .ko('스프링')
    .zhHans('弹簧')
    .zhHant('彈簧')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Decay')
    .es('Decai')
    .pt('Decaimento')
    .fr(1)
    .it('Decadimento')
    .ja('ディケイ')
    .ko('디케이')
    .zhHans('衰减')
    .zhHant('衰減')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='+DRY')
    .es(1)
    .pt(1)
    .fr(1)
    .it('+ORIG')
    .ja('＋原音')
    .ko('+원음')
    .zhHans('+干声')
    .zhHant('+乾聲')
    .ar(0)
    .he(0)
)

