from pbt.translations import *


ts = TranslationSet()

ts.append(T(tag="ClumpLabel/text",
    text='CROSSFEED')
    .es(1)
    .pt(1)
    .fr(1)
    .ja('クロスフィード')
    .ko('크로스피드')
    .zhHans('互馈效果')
    .zhHant('互饋效果')
    .ar('الكروسفِيد')
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='EQUALIZATION')
    .es('ECUALIZACIÓN')
    .pt('EQUALIZAÇÃO')
    .fr('ÉGALISATION')
    .ja('イコライゼーション')
    .ko('EQ')
    .zhHans('频率均衡器')
    .zhHant('頻率均衡器')
    .ar('موازنة الترددات')
    .he(0)
)

ts.append(T(tag="HUD/state",
    text='Safe')
    .es('Anticlipping')
    .pt('Segurança')
    .fr('Précaution')
    .ja('セーフ')
    .ko('세이프')
    .zhHans('安全')
    .zhHant('安全')
    .ar('الحذَرِ')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Amount')
    .es('Intensidad')
    .pt('Quantidade')
    .fr('Intensité')
    .ja('量')
    .ko('정도')
    .zhHans('量')
    .zhHant('量')
    .ar('الكمية')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Angle')
    .es('Ángulo')
    .pt('Ângulo')
    .fr(1)
    .ja('角度')
    .ko('각도')
    .zhHans('角度')
    .zhHant('角度')
    .ar('الزاوية')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Bass')
    .es('Bajos')
    .pt('Grave')
    .fr('Graves')
    .ja('低域')
    .ko('저역대')
    .zhHans('低频')
    .zhHant('低頻')
    .ar(' الباس')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Bass Frequency')
    .es('Frecuencia bajos')
    .pt('Frequência – Grave')
    .fr('Basses Fréquences')
    .ja('低域周波数')
    .ko('저역대 필터 기준')
    .zhHans('低频')
    .zhHant('低頻')
    .ar('تردد الباس')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Compensation')
    .es('Compensación')
    .pt('Compensação')
    .fr(1)
    .ja('補償')
    .ko('보상')
    .zhHans('补偿')
    .zhHant('補償')
    .ar('التعويض')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Crossfeed Realism')
    .es('Realismo de Crossfeed')
    .pt('Realismo do Crossfeed')
    .fr('Qualité du Crossfeed')
    .ja('クロスフィードリアリズム')
    .ko('크로스피드 리얼리즘')
    .zhHans('互馈真实度')
    .zhHant('互饋真實度')
    .ar('واقِعيةُ الكروسفِيد')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Dim Level')
    .es('Nivel de atenuación')
    .pt('Nível de Atenuação')
    .fr("Niveau d'Atténuation")
    .ja('ディムレベル')
    .ko('Dim 레벨')
    .zhHans('电平衰减')
    .zhHant('電平衰減')
    .ar('مستوَى التخفيف')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Dither')
    .es('Interpolación')
    .pt(1)
    .fr(1)
    .ja('ディザー')
    .ko('디더')
    .zhHans('抖动')
    .zhHant('抖動')
    .ar(' الديثر')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='L/R Balance')
    .es('Balance L/R')
    .pt('Equilíbrio L/R')
    .fr('Équilibre L/R')
    .ja('L/Rバランス')
    .ko('좌/우 밸런스')
    .zhHans('L/R平衡')
    .zhHant('L/R平衡')
    .ar('L/R توازن')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Output')
    .es('Salida')
    .pt('Saída')
    .fr('Sortie')
    .ja('アウトプット')
    .ko('아웃풋')
    .zhHans('输出')
    .zhHant('輸出')
    .ar('إشارة الإخراج')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Safe Gain')
    .es('Anticlipping')
    .pt('Ganho de Segurança')
    .fr('Gain de Précaution')
    .ja('セーフゲイン')
    .ko('세이프 게인')
    .zhHans('安全增益')
    .zhHant('安全增益')
    .ar('ربحُ الحذَرِ')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Soft Start Time')
    .es('Fundido de entrada')
    .pt('Tempo de Fade In')
    .fr('Temps de Fondu')
    .ja('ソフトスタート時間')
    .ko('페이드인 타임')
    .zhHans('淡入时间')
    .zhHant('淡入時間')
    .ar('وَقتُ التضاؤُل')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Treble')
    .es('Altos')
    .pt('Agudo')
    .fr('Aigus')
    .ja('高域')
    .ko('고역대')
    .zhHans('高频')
    .zhHant('高頻')
    .ar('الصوتُ العالي')
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Treble Frequency')
    .es('Frecuencia altos')
    .pt('Frequência – Agudo')
    .fr('Hautes Fréquences')
    .ja('高域周波数')
    .ko('고역대 필터 기준')
    .zhHans('高频')
    .zhHant('高頻')
    .ar('تردد الصوتُ العالي')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Dim')
    .es('Atenuación')
    .pt('Atenuar')
    .fr('Atténuation')
    .ja('ディム')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('التخفيف')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Flip L/R')
    .es('Trocar L/R')
    .pt('Inverter L/R')
    .fr('Inverser L/R')
    .ja('L/R入れ替え')
    .ko('좌/우 뒤집기')
    .zhHans('L/R翻转')
    .zhHant('L/R翻轉')
    .ar(' L/R عَكّس')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Mono')
    .es(1)
    .pt(1)
    .fr(1)
    .ja('モノラル')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('مونو')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='Polarity')
    .es('Polaridad')
    .pt('Polaridade')
    .fr('Polarité')
    .ja('極')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('القطبية')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="CrossfeedRealism",
    text='Hyperrealistic')
    .es('Muy realista')
    .pt('Mais Realista')
    .fr('Très Réaliste')
    .ja('超リアル')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('اكثرُ واقعيةٌ')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="CrossfeedRealism",
    text='Realistic')
    .es('Más realista')
    .pt('Realista')
    .fr('Réaliste')
    .ja('リアル')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('واقعي')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="CrossfeedRealism",
    text='Standard')
    .es('Estándar')
    .pt('Padrão')
    .fr('Normale')
    .ja('普通')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('عادي')
    .he(0)
)

ts.append(T(tag="Tagline",
    text='Conjure speakers from your headphones.')
    .es('Simula altavoces desde tus audífonos.')
    .pt('Transforme seu fone em um par de caixas.')
    .fr('Transformez votre casque en enceintes de monitoring.')
    .ja('ヘッドフォンにスピーカーをインストール')
    .ko('헤드폰에 스피커를 가져오는 마술')
    .zhHans('用耳机营造出音箱般的音响效果')
    .zhHant('用耳機營造出喇叭般的音響效果')
    .ar('حول سماعات الرأس إلى مكبرات صوت')
    .he(0)
)

