from pbtranslations.translations import *


ts = TranslationSet()

ts.append(T(tag="Parameter/option",
    context="TiltLoudnessMode",
    text='Auto')
    # in the sense of 'automatic'
    .es(1)
    .pt('Automático')
    .fr('Automatique')
    .it(1)
    .ja('自動')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('أوتوماتيكي')
    )

ts.append(T(tag="Parameter/option",
    context="TiltLoudnessMode",
    text='Standard')
    .es('Estándar')
    .pt('Padrão')
    .fr('Normal')
    .it(1)
    .ja('普通')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('عادي')
    )

ts.append(T(tag="Parameter/option",
    context="TiltLoudnessMode",
    text='Treble')
    .es('Agudos')
    .pt('Agudo')
    .fr('Aigu')
    .it('Alte')
    .ja('高域')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('الصوت العالي')
    )

ts.append(T(tag="Parameter/option",
    context="TiltLoudnessMode",
    text='Bass')
    .es('Graves')
    .pt('Grave')
    .fr('Grave')
    .it('Basse')
    .ja('低域')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('الباس')
    )

ts.append(T(tag="Tagline",
    text='Superior tone-shaping, from mix to master')
    .es('Modelado de tonos sensacional, de la mezcla al máster')
    .pt('Modelagem excelente de tonalidade, da mix à master')
    .fr('Excellent tone-shaping, du mix au master')
    .it('Modellamento del tono superiore, dal missaggio al master')
    .ja('周波数の鋭利なピックアップとトーンシェーピング')
    .ko('믹싱에서 마스터링까지 아우르는 간결한 톤 쉐이핑')
    .zhHans('从混音到母带的超级音色塑造')
    .zhHant('從混音到母帶的超級音色塑造')
    .ar('تسوية نِغم ممتازة،من الميكس إِلَى الماستر')
    )

ts.append(T(tag="ClumpLabel/text",
    text='G\nA\nI\nN')
    # Set vertically
    .es('GA\nNAN\nCIA')
    .pt('GA\nNH\nO')
    .fr(1)
    .it('G\nU\nA\nD')
    .ja('ゲ\nイ\nン')
    .ko('게\n인')
    .zhHans('增\n益')
    .zhHant('增\n益')
    .ar('الربح')
    )

ts.append(T(tag="ClumpLabel/text",
    text='R\nA\nN\nG\nE')
    # Set vertically
    .es('R\nA\nN\nG\nO')
    .pt('EX\nTE\nNS\nÃO')
    .fr('G\nA\nM\nM\nE')
    .it('G\nA\nM\nM\nA')
    .ja('範\n囲')
    .ko('적\n용\n범\n위')
    .zhHans('范\n围')
    .zhHant('範\n圍')
    .ar('المدى')
    )

ts.append(T(tag="ClumpLabel/text",
    text='R\nA\nN\nG\nE')
    # Set vertically
    .es('R\nA\nN\nG\nO')
    .pt('EX\nTE\nNS\nÃO')
    .fr('G\nA\nM\nM\nE')
    .it('G\nA\nM\nM\nA')
    .ja('範\n囲')
    .ko('적\n용\n범\n위')
    .zhHans('范\n围')
    .zhHant('範\n圍')
    .ar('المدى')
    )

ts.append(T(tag="ClumpLabel/text",
    text='FILTER')
    .es('FILTRO')
    .pt('FILTRO')
    .fr('FILTRE')
    .it('FILTRO')
    .ja('フィルター')
    .ko('필터')
    .zhHans('滤波')
    .zhHant('濾波')
    .ar('الفلتر')
    )

ts.append(T(tag="ParamLabel/text",
    text='Loudness')
    .es('Volumen')
    .pt('Intensidade')
    .fr('Sonie')
    .it('Volume')
    .ja('ラウドネス')
    .ko('음량')
    .zhHans('响度')
    .zhHant('響度')
    .ar('مستوَى الصوت')
    )

ts.append(T(tag="ParamLabel/text",
    text='Output Gain')
    .es('Ganancia de Salida')
    .pt('Ganho de Saída')
    .fr('Gain de Sortie')
    .it('Guadagno Uscita')
    .ja('アウトプットゲイン')
    .ko('아웃풋 게인')
    .zhHans('输出增益')
    .zhHant('輸出增益')
    .ar('رِبح إشارة الإخراج')
    )

ts.append(T(tag="ClumpLabel/text",
    text='ADV FILTER')
    .es('FILTRO EXT')
    .pt('FILTRO +')
    .fr('FILTRE EXT')
    .it('FILTRO AVN')
    .ja('フィルター微調整')
    .ko('세부 필터')
    .zhHans('高級濾波調節')
    .zhHant('進階濾波調節')
    .ar('فلتر مُفصَّل')
    )

ts.append(T(tag="ClumpLabel/text",
    text='LOW')
    .es('BAJOS')
    .pt('GRAVE')
    .fr('GRAVES')
    .it('BASSE')
    .ja('低域')
    .ko('저역대')
    .zhHans('低频')
    .zhHant('低頻')
    .ar('منخفض')
    )

ts.append(T(tag="ClumpLabel/text",
    text='HIGH')
    .es('ALTOS')
    .pt('AGUDO')
    .fr('AIGUS')
    .it('ALTE')
    .ja('高域')
    .ko('고역대')
    .zhHans('高频')
    .zhHant('高頻')
    .ar('مرتفع')
    )

ts.append(T(tag="ParamLabel/text",
    text='Slope')
    .es('Pendiente')
    .pt('Declive')
    .fr('Ordre')
    .it('Pendenza')
    .ja('スロープ')
    .ko('필터 기울기')
    .zhHans('坡度')
    .zhHant('坡度')
    .ar('الميل')
    )

ts.append(T(tag="ParamLabel/text",
    text='Resonance')
    .es('Resonancia')
    .pt('Ressonância')
    .fr('Résonance')
    .it('Risonanza')
    .ja('レゾナンス')
    .ko('레저넌스')
    .zhHans('谐振')
    .zhHant('諧振')
    .ar('الرنين')
    )

ts.append(T(tag="ParamLabel/text",
    text='Slope')
    .es('Pendiente')
    .pt('Declive')
    .fr('Ordre')
    .it('Pendenza')
    .ja('スロープ')
    .ko('필터 기울기')
    .zhHans('坡度')
    .zhHant('坡度')
    .ar('الميل')
    )

ts.append(T(tag="ParamLabel/text",
    text='Resonance')
    .es('Resonancia')
    .pt('Ressonância')
    .fr('Résonance')
    .it('Risonanza')
    .ja('レゾナンス')
    .ko('레저넌스')
    .zhHans('谐振')
    .zhHant('諧振')
    .ar('الرنين')
    )

