from pbt.translations import *


ts = TranslationSet()

ts.append(T("ParamLabel/text", "0", "Auto|Blanking")
    .es("Supresión|automática")
    .pt("Desligamento|Automático")
    .fr("Silence|Automatique")
    .ja("オートブランキング")
    .ko("자동 차단 기능")
    .zhHans("自动消隐")
    .zhHant("自動消隱")
    .ar("المسح التلقائي")
    .he(0)
)

ts.append(T("ParamLabel/text", "0", "Bit|Depth")
    .es("Profundidad|de bit")
    .pt("Profundidade|em Bits")
    .fr("Niveau de|Quantification")
    .ja("ビットデプス")
    .ko("비트 뎁스")
    .zhHans("比特深度")
    .zhHant("比特深度")
    .ar("عمق البِت")
    .he(0)
)

ts.append(T("ParamLabel/text", "0", "Dither|Amount")
    .es("Nivel de|interpolación")
    .pt("Quantidade|de Dither")
    .fr("Intensité|du Dither")
    .ja("ディザー量")
    .ko("디더 적용 정도")
    .zhHans("抖动量")
    .zhHant("抖動量")
    .ar("كمية الديثر")
    .he(0)
)

ts.append(T("ParamLabel/text", "0", "Noise|Shaping")
    .es("Modelación|de ruido")
    .pt("Modelagem|do Ruído")
    .fr("Formage|de Bruit")
    .ja("ノイズシェーピング")
    .ko("노이즈 형태")
    .zhHans("噪音整形")
    .zhHant("噪音整形")
    .ar("تشكيل الضجيج")
    .he(0)
)

ts.append(T("Parameter/option", "BitDepth", "Pass Thru")
    .es("Señal limpia")
    .pt("Sinal Limpo")
    .fr("Laissez-Passer")
    .ja("そのまま")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("تجَاوز")
    .he(0)
)

ts.append(T("Parameter/option", "DitherAmount", "High")
    .es("Alto")
    .pt("Alto")
    .fr("Haute")
    .ja("多め")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("مرتفع")
    .he(0)
)

ts.append(T("Parameter/option", "DitherAmount", "Low")
    .es("Bajo")
    .pt("Baixo")
    .fr("Basse")
    .ja("少なめ")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("منخفض")
    .he(0)
)

ts.append(T("Parameter/option", "DitherAmount", "None")
    .es("Nulo")
    .pt("Nenhum")
    .fr("Nulle")
    .ja("なし")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("لا شيء")
    .he(0)
)

ts.append(T("Parameter/option", "DitherAmount", "Optimal")
    .es("Óptimo")
    .pt("Otimizado")
    .fr("Optimale")
    .ja("最適")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("مثالي")
    .he(0)
)

ts.append(T("Parameter/option", "NoiseShaping", "High")
    .es("Alta")
    .pt("Alto")
    .fr("Haut")
    .ja("多め")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("مرتفع")
    .he(0)
)

ts.append(T("Parameter/option", "NoiseShaping", "Low")
    .es("Baja")
    .pt("Baixo")
    .fr("Bas")
    .ja("少なめ")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("منخفض")
    .he(0)
)

ts.append(T("Parameter/option", "NoiseShaping", "Medium")
    .es("Medio")
    .pt("Médio ")
    .fr("Moyen")
    .ja("普通")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("متوسط")
    .he(0)
)

ts.append(T("Parameter/option", "NoiseShaping", "None")
    .es("Nula")
    .pt("Nenhum")
    .fr("Nul")
    .ja("なし")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("لا شيء")
    .he(0)
)

ts.append(T("Parameter/option", "NoiseShaping", "Optimal")
    .es("Óptima")
    .pt("Otimizado")
    .fr(1)
    .ja("最適")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("مثالي")
    .he(0)
)

print(ts)