from pbt.translations import *


ts = TranslationSet()

ts.append(T(tag="ClumpLabel/text",
    text='FILTER')
    .es(0)
    .pt(0)
    .fr('FILTRE')
    .ja('フィルター')
    .ko('필터')
    .zhHans('滤波')
    .zhHant('濾波')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='TILT')
    .es(0)
    .pt(0)
    .fr('INCL')
    .ja('チルト')
    .ko('틸트')
    .zhHans('倾斜')
    .zhHant('傾斜')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Bias')
    .es(0)
    .pt(0)
    .fr('Tension')
    .ja('バイアス')
    .ko('바이어스')
    .zhHans('交流偏磁')
    .zhHant('交流偏磁')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='DRY')
    .es(0)
    .pt(0)
    .fr(1)
    .ja('原音')
    .ko('원음')
    .zhHans('干声')
    .zhHant('乾聲')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Drive')
    .es(0)
    .pt(0)
    .fr(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Noise')
    .es(0)
    .pt(0)
    .fr('Bruit')
    .ja('ノイズ')
    .ko('노이즈')
    .zhHans('噪声')
    .zhHant('噪聲')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text='Output')
    .es(0)
    .pt(0)
    .fr(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="FilterPosition",
    text='Post')
    .es(0)
    .pt(0)
    .fr(1)
    .ja('ポスト')
    .ko('포스트')
    .zhHans('后')
    .zhHant('後')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="FilterPosition",
    text='Pre')
    .es(0)
    .pt(0)
    .fr('Pré')
    .ja('プリ')
    .ko('프리')
    .zhHans('前')
    .zhHant('前')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="TubeTapeOrder",
    text='Tape -> Tube')
    .es(0)
    .pt(0)
    .fr(1)
    .ja('テープ -> チューブ')
    .ko('테이프 -> 진공관')
    .zhHans('磁帶 -> 真空管')
    .zhHant('磁帶 -> 真空管')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="TubeTapeOrder",
    text='Tube -> Tape')
    .es(0)
    .pt(0)
    .fr(1)
    .ja('チューブ -> テープ')
    .ko('진공관 -> 테이프')
    .zhHans('真空管 -> 磁带')
    .zhHant('真空管 -> 磁帶')
    .ar(0)
    .he(0)
)

ts.append(T(tag="Tagline",
    text='Tube + Tape = Tupe')
    .es(0)
    .pt(0)
    .fr(1)
    .ja('チューブ + テープ = チュープ')
    .ko('진공관 + 테이프 = 튜프')
    .zhHans('真空管 + 磁带 = Tupe')
    .zhHant('真空管 + 磁帶 = Tupe')
    .ar(0)
    .he(0)
)

