from pbtranslations.translations import *


ts = TranslationSet()

ts.append(T(tag="Parameter/option",
    context="SoftClipReadout",
    text='LMTR GR')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    context="SoftClipReadout",
    text='LUFS (LT)')
    .es('LUFS (LP)')
    .pt('LUFS (LP)')
    .fr('LUFS (LT)')
    .it('LUFS (LT)')
    .ja('LUFS (長期)')
    .ko('LUFS (장기)')
    .zhHans('LUFS (长期)')
    .zhHant('LUFS (長期)')
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    context="SoftClipReadout",
    text='LRA')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterBrickwall",
    text='Follows Mix')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterBrickwall",
    text='Brickwall')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('ブリックウォール')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    context="SoftClipGainComp",
    text='Auto')
    .es('Automático')
    .pt('Automático')
    .fr('Automatique')
    .it('Automatico')
    .ja('自動')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('تلقائي')
    )

ts.append(T(tag="Parameter/option",
    context="SoftClipGainComp",
    text='Manual')
    .es(1)
    .pt(1)
    .fr('Manuel')
    .it('Manuale')
    .ja('手動')
    .ko('수동')
    .zhHans('手动')
    .zhHant('手動')
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    context="SidechainSource",
    text='internal')
    .es('interna')
    .pt('interna')
    .fr('interne')
    .it('interna')
    .ja('内部')
    .ko('인터널')
    .zhHans('内部')
    .zhHant('內部')
    .ar('داخلي')
    )

ts.append(T(tag="Parameter/option",
    context="SidechainSource",
    text='external')
    .es('externa')
    .pt('externa')
    .fr('externe')
    .it('esterna')
    .ja('外部')
    .ko('엑스터널')
    .zhHans('外部')
    .zhHant('外部')
    .ar('خارجي')
    )

ts.append(T(tag="Parameter/option",
    context="CompLinkMode",
    text='Left/Right')
    .es('Izquierda/Derecha')
    .pt('Esquerda/Direita')
    .fr('Gauche/Droite')
    .it('Sinistra/Destra')
    .ja('左/右')
    .ko('좌/우')
    .zhHans('左/右')
    .zhHant('左/右')
    .ar('يمين/يسار')
    )

ts.append(T(tag="Parameter/option",
    context="CompLinkMode",
    text='Mid/Side')
    .es(1)
    .pt('Meio/Lados')
    .fr(1)
    .it('Centro/Lati')
    .ja('ミッド/サイド')
    .ko('미드/사이드')
    .zhHans('中/侧')
    .zhHant('中/側')
    .ar('ميد/سايد')
    )

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterLink",
    text='Off')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterLink",
    text='Hybrid')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterLink",
    text='Full')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Soft Clip')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('ソフトクリップ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Sidechain')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('サイドチェイン')
    .ko('사이드체인')
    .zhHans('旁链')
    .zhHant('旁鏈')
    .ar('السايدشين')
    )

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Linking')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="Tagline",
    text='Vulf Compressor Mastering Edition')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='ratio')
    .es('proporción')
    .pt('proporção')
    .fr(1)
    .it('rapporto')
    .ja('比率')
    .ko('비율')
    .zhHans('比率')
    .zhHant('比率')
    .ar('نسبة الضغط')
    )

ts.append(T(tag="ClumpLabel/text",
    text='thresh')
    .es('umbral')
    .pt('limite')
    .fr('seuil')
    .it('soglia')
    .ja('スレッショルド')
    .ko('기준 레벨')
    .zhHans('阈')
    .zhHant('閾')
    .ar('حد العتبة')
    )

ts.append(T(tag="ClumpLabel/text",
    text='makeup')
    .es('compensación')
    .pt('compensação')
    .fr('compensation')
    .it('compensazione')
    .ja('補償')
    .ko('보상')
    .zhHans('补偿')
    .zhHant('補償')
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    text='apply')
    .es('aplicar')
    .pt('aplicar')
    .fr('appliquer')
    .it('applica')
    .ja('適用する')
    .ko('적용')
    .zhHans('应用')
    .zhHant('應用')
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='attack')
    .es('ataque')
    .pt('ataque')
    .fr('attaque')
    .it('attacco')
    .ja('アタック')
    .ko('어택 타임')
    .zhHans('起动时间')
    .zhHant('起動時間')
    .ar('زمن التطبيق')
    )

ts.append(T(tag="ClumpLabel/text",
    text='release')
    .es('relajación')
    .pt('repouso')
    .fr('retour')
    .it('rilascio')
    .ja('リリース')
    .ko('릴리즈 타임')
    .zhHans('释放时间')
    .zhHant('釋放時間')
    .ar('التحرير')
    )

ts.append(T(tag="ClumpLabel/text",
    text='style')
    .es('estilo')
    .pt('estilo')
    .fr(1)
    .it('stile')
    .ja('スタイル')
    .ko('스타일')
    .zhHans('样式')
    .zhHant('類型')
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='dry')
    .es(1)
    .pt(1)
    .fr(1)
    .it('orig')
    .ja('原音')
    .ko('원음')
    .zhHans('干声')
    .zhHant('乾聲')
    .ar('جاف')
    )

ts.append(T(tag="ClumpLabel/text",
    text='vcme')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    text='comp')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('コンプ')
    .ko('컴프')
    .zhHans('压缩')
    .zhHant('壓縮')
    .ar('الضغط')
    )

ts.append(T(tag="Parameter/option",
    text='soft clip')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('ソフトクリップ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    text='saturation')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='slew')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="Parameter/option",
    text='limiter')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='slew')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='in')
    .es('entrada')
    .pt('entrada')
    .fr('entrée')
    .it('ingr')
    .ja('イン')
    .ko('인풋')
    .zhHans('输入')
    .zhHant('輸入')
    .ar('دَخْل')
    )

ts.append(T(tag="ClumpLabel/text",
    text='drive')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('ドライブ')
    .ko('드라이브')
    .zhHans('输入')
    .zhHant('輸入')
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='mix')
    .es('mezcla')
    .pt(1)
    .fr(1)
    .it('miscela')
    .ja('ミックス')
    .ko('믹스')
    .zhHans('混合')
    .zhHant('混合')
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='out')
    .es('salida')
    .pt('saída')
    .fr('sortie')
    .it('uscita')
    .ja('アウト')
    .ko('아웃풋')
    .zhHans('输出')
    .zhHant('輸出')
    .ar('خَرْج')
    )

ts.append(T(tag="ParamLabel/text",
    text='tilt')
    .es('incl')
    .pt('incl')
    .fr('incl')
    .it('pend')
    .ja('チルト')
    .ko('틸트')
    .zhHans('倾斜')
    .zhHant('傾斜')
    .ar(0)
    )

ts.append(T(tag="ParamLabel/text",
    text='trim')
    .es('ajuste')
    .pt('volume')
    .fr('volume')
    .it('vol')
    .ja('トリム')
    .ko('트림')
    .zhHans('调整')
    .zhHant('調整')
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='source')
    .es('fuente')
    .pt('fonte')
    .fr(1)
    .it('sorgente')
    .ja('音源')
    .ko('소스')
    .zhHans('声源')
    .zhHant('聲源')
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='blend')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='comp')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('コンプ')
    .ko('컴프')
    .zhHans('压缩')
    .zhHant('壓縮')
    .ar('الضغط')
    )

ts.append(T(tag="ClumpLabel/text",
    text='link amount')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='side trim')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='mode')
    .es('modo')
    .pt('modo')
    .fr(1)
    .it('modalità')
    .ja('モード')
    .ko('모드')
    .zhHans('模式')
    .zhHant('模式')
    .ar('الوضع')
    )

ts.append(T(tag="ClumpLabel/text",
    text='left/right')
    .es('izquierda/derecha')
    .pt('esquerda/direita')
    .fr('gauche/droite')
    .it('sinistra/destra')
    .ja('左/右')
    .ko('좌/우')
    .zhHans('左/右')
    .zhHant('左/右')
    .ar('يمين/يسار')
    )

ts.append(T(tag="ClumpLabel/text",
    text='front/back')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='soft clip')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('ソフトクリップ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='limiter link')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='side trim')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='lfe')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='link amount')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='link trim')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='center')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='link amount')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

ts.append(T(tag="ClumpLabel/text",
    text='link trim')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    )

