from pbtranslations.translations import *


ts = TranslationSet()

ts.append(T(tag="Parameter/option",
    context="SoftClipReadout",
    text='LMTR GR')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('リミターGR')
    .ko('리미터 GR')
    .zhHans('限幅GR')
    .zhHant('限幅GR')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipReadout",
    text='LUFS (LT)')
    .es('LUFS (LP)')
    .pt('LUFS (LP)')
    .fr('LUFS (LT)')
    .it('LUFS (LT)')
    .ja('LUFS (長期)')
    .ko('LUFS (장기)')
    .zhHans('LUFS (长期)')
    .zhHant('LUFS (長期)')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipReadout",
    text='LRA')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterBrickwall",
    text='Follows Mix')
    .es('Seguir Mezcla')
    .pt('Seguir Mix')
    .fr('Suivre Mix')
    .it('Segue Miscela')
    .ja('ミックスに従う')
    .ko('믹스 연동')
    .zhHans('混音联动')
    .zhHant('混音聯動')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterBrickwall",
    text='Brickwall')
    .es(1)
    .pt(1)
    .fr(1)
    .it('Muro')
    .ja('ブリックウォール')
    .ko('브릭월')
    .zhHans('砖墙限幅')
    .zhHant('磚牆限幅')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipGainComp",
    text='Auto')
    .es('Automático')
    .pt('Automático')
    .fr('Automatique')
    .it('Automatico')
    .ja('自動')
    .ko('자동')
    .zhHans('自动')
    .zhHant('自動')
    .ar('تلقائي')
)

ts.append(T(tag="Parameter/option",
    context="SoftClipGainComp",
    text='Manual')
    .es(1)
    .pt(1)
    .fr('Manuel')
    .it('Manuale')
    .ja('手動')
    .ko('수동')
    .zhHans('手动')
    .zhHant('手動')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SidechainSource",
    text='internal')
    .es('interna')
    .pt('interna')
    .fr('interne')
    .it('interna')
    .ja('内部')
    .ko('인터널')
    .zhHans('内部')
    .zhHant('內部')
    .ar('داخلي')
)

ts.append(T(tag="Parameter/option",
    context="SidechainSource",
    text='external')
    .es('externa')
    .pt('externa')
    .fr('externe')
    .it('esterna')
    .ja('外部')
    .ko('엑스터널')
    .zhHans('外部')
    .zhHant('外部')
    .ar('خارجي')
)

ts.append(T(tag="Parameter/option",
    context="CompLinkMode",
    text='Left/Right')
    .es('Izquierda/Derecha')
    .pt('Esquerda/Direita')
    .fr('Gauche/Droite')
    .it('Sinistra/Destra')
    .ja('左/右')
    .ko('좌/우')
    .zhHans('左/右')
    .zhHant('左/右')
    .ar('يمين/يسار')
)

ts.append(T(tag="Parameter/option",
    context="CompLinkMode",
    text='Mid/Side')
    .es('Central/Lateral')
    .pt('Meio/Lados')
    .fr(1)
    .it('Centro/Lati')
    .ja('ミッド/サイド')
    .ko('미드/사이드')
    .zhHans('中/侧')
    .zhHant('中/側')
    .ar('ميد/سايد')
)

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterLink",
    text='Off')
    .es('Des.')
    .pt('Des.')
    .fr(1)
    .it('Spento')
    .ja('オフ')
    .ko('오프')
    .zhHans('关')
    .zhHant('關')
    .ar(1)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterLink",
    text='Hybrid')
    .es('Híbrido')
    .pt('Híbrido')
    .fr('Hybride')
    .it('Ibrido')
    .ja('ハイブリッド')
    .ko('하이브리드')
    .zhHans('混合')
    .zhHant('混合')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="SoftClipLimiterLink",
    text='Full')
    .es('Completo')
    .pt('Total')
    .fr('Complet')
    .it('Totale')
    .ja('フル')
    .ko('풀')
    .zhHans('全开')
    .zhHant('全開')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Soft Clip')
    .es('Clip Suave')
    .pt(1)
    .fr(1)
    .it('Clip Lieve')
    .ja('ソフトクリップ')
    .ko('소프트 클립')
    .zhHans('软削波')
    .zhHant('軟削波')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Sidechain')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('サイドチェイン')
    .ko('사이드 체인')
    .zhHans('旁链')
    .zhHant('旁鏈')
    .ar('السايدشين')
)

ts.append(T(tag="Parameter/option",
    context="AdvPage",
    text='Linking')
    .es('Enlace')
    .pt(1)
    .fr('Couplage')
    .it('Accoppiamento')
    .ja('リンク')
    .ko('링크 설정')
    .zhHans('连结')
    .zhHant('連結')
    .ar('الوصل')
)

ts.append(T(tag="Tagline",
    text='Vulf Compressor Mastering Edition')
    .es('Vulf Compressor Edición de Masterización')
    .pt('Vulf Compressor Edição de Masterização')
    .fr('Vulf Compressor Édition Mastering')
    .it('Vulf Compressor Versione Mastering')
    .ja('Vulf Compressor マスタリングバージョン')
    .ko('Vulf Compressor 마스터링 에디션')
    .zhHans('Vulf Compressor 母带版')
    .zhHant('Vulf Compressor 母帶版')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='comp gr')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('コンプgr')
    .ko('컴프 gr')
    .zhHans('压缩gr')
    .zhHant('壓縮gr')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='ratio')
    .es('proporción')
    .pt('proporção')
    .fr(1)
    .it('rapporto')
    .ja('比率')
    .ko('비율')
    .zhHans('比率')
    .zhHant('比率')
    .ar('نسبة الضغط')
)

ts.append(T(tag="ClumpLabel/text",
    text='thresh')
    .es('umbral')
    .pt('limite')
    .fr('seuil')
    .it('soglia')
    .ja('スレッショルド')
    .ko('기준 레벨')
    .zhHans('阈')
    .zhHant('閾')
    .ar('حد العتبة')
)

ts.append(T(tag="ClumpLabel/text",
    text='makeup')
    .es('compensación')
    .pt('compensação')
    .fr('compensation')
    .it('compensazione')
    .ja('補償')
    .ko('보상')
    .zhHans('补偿')
    .zhHant('補償')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    text='apply')
    .es('aplicar')
    .pt('aplicar')
    .fr('appliquer')
    .it('applica')
    .ja('適\n用\nす\nる')
    .ko('적\n용')
    .zhHans('应\n用')
    .zhHant('應\n用')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='attack')
    .es('ataque')
    .pt('ataque')
    .fr('attaque')
    .it('attacco')
    .ja('アタック')
    .ko('어택 타임')
    .zhHans('起动时间')
    .zhHant('起動時間')
    .ar('زمن التطبيق')
)

ts.append(T(tag="ClumpLabel/text",
    text='release')
    .es('relajación')
    .pt('repouso')
    .fr('retour')
    .it('rilascio')
    .ja('リリース')
    .ko('릴리즈 타임')
    .zhHans('释放时间')
    .zhHant('釋放時間')
    .ar('التحرير')
)

ts.append(T(tag="ClumpLabel/text",
    text='style')
    .es('estilo')
    .pt('estilo')
    .fr(1)
    .it('stile')
    .ja('スタイル')
    .ko('스타일')
    .zhHans('样式')
    .zhHant('樣式')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='dry')
    .es(1)
    .pt(1)
    .fr(1)
    .it('orig')
    .ja('原音')
    .ko('원음')
    .zhHans('干声')
    .zhHant('乾聲')
    .ar('جاف')
)

ts.append(T(tag="ClumpLabel/text",
    text='vcme')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    text='comp')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('コンプ')
    .ko('컴프')
    .zhHans('压缩')
    .zhHant('壓縮')
    .ar('الضغط')
)

ts.append(T(tag="Parameter/option",
    text='soft clip')
    .es('clip suave')
    .pt(1)
    .fr(1)
    .it('clip lieve')
    .ja('ソフトクリップ')
    .ko('소프트 클립')
    .zhHans('软削峰')
    .zhHant('軟削峰')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    text='saturation')
    .es('saturación')
    .pt('saturação')
    .fr(1)
    .it('saturazione')
    .ja('サチュレーション')
    .ko('새츄레이션')
    .zhHans('饱和')
    .zhHant('飽和')
    .ar('التشبع')
)

ts.append(T(tag="ClumpLabel/text",
    text='slew')
    .es(1)
    .pt('variação')
    .fr('balayage')
    .it('viscosità')
    .ja('スルー')
    .ko('슬루')
    .zhHans('斜率')
    .zhHant('斜率')
    .ar(0)
)

ts.append(T(tag="Parameter/option",
    text='limiter')
    .es('limitador')
    .pt(1)
    .fr('limiteur')
    .it('limitatore')
    .ja('リミター')
    .ko('리미터')
    .zhHans('限幅器')
    .zhHant('限幅器')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='slew')
    .es(1)
    .pt('variação')
    .fr('balayage')
    .it('viscosità')
    .ja('スルー')
    .ko('슬루')
    .zhHans('斜率')
    .zhHant('斜率')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='in')
    .es('entrada')
    .pt('entrada')
    .fr('entrée')
    .it('ingresso')
    .ja('イン')
    .ko('인풋')
    .zhHans('输入')
    .zhHant('輸入')
    .ar('دَخْل')
)

ts.append(T(tag="ClumpLabel/text",
    text='drive')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('ドライブ')
    .ko('드라이브')
    .zhHans('驱动')
    .zhHant('驅動')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='mix')
    .es('mezcla')
    .pt(1)
    .fr(1)
    .it('miscela')
    .ja('ミックス')
    .ko('믹스')
    .zhHans('混合')
    .zhHant('混合')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='out')
    .es('salida')
    .pt('saída')
    .fr('sortie')
    .it('uscita')
    .ja('アウト')
    .ko('아웃풋')
    .zhHans('输出')
    .zhHant('輸出')
    .ar('خَرْج')
)

ts.append(T(tag="ParamLabel/text",
    text='tilt')
    .es('incl')
    .pt('incl.')
    .fr('incl')
    .it('pend')
    .ja('チルト')
    .ko('틸트')
    .zhHans('倾斜')
    .zhHant('傾斜')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='trim')
    .es('ajuste')
    .pt('volume')
    .fr('volume')
    .it('vol')
    .ja('トリム')
    .ko('트림')
    .zhHans('调整')
    .zhHant('調整')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='source')
    .es('fuente')
    .pt('fonte')
    .fr(1)
    .it('sorgente')
    .ja('音源')
    .ko('소스')
    .zhHans('声源')
    .zhHant('聲源')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='blend')
    .es('mezcla')
    .pt('mescla')
    .fr('mélange')
    .it('miscela')
    .ja('ブレンド')
    .ko('블렌드')
    .zhHans('混合')
    .zhHant('混合')
    .ar('مزج ال')
)

ts.append(T(tag="ClumpLabel/text",
    text='Comp')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('コンプ')
    .ko('컴프')
    .zhHans('压缩')
    .zhHant('壓縮')
    .ar('الضغط')
)

ts.append(T(tag="ParamLabel/text",
    text='mode')
    .es('modo')
    .pt('modo')
    .fr(1)
    .it('modalità')
    .ja('モード')
    .ko('모드')
    .zhHans('模式')
    .zhHant('模式')
    .ar('الوضع')
)

ts.append(T(tag="ParamLabel/text",
    text='side trim')
    .es('ajuste lateral')
    .pt('volume dos lados')
    .fr('volume du side')
    .it('volume lati')
    .ja('サイドトリム')
    .ko('사이드 트림')
    .zhHans('侧声道调节')
    .zhHant('側聲道調節')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='stereo link')
    .es('link estéreo')
    .pt('link estéreo')
    .fr('couplage stéréo')
    .it('accoppiamento stereo')
    .ja('ステレオリンク')
    .ko('스테레오 링크')
    .zhHans('双声道连结')
    .zhHant('雙聲道連結')
    .ar('الوصل إستيريو')
)

ts.append(T(tag="ParamLabel/text",
    text='left/right link')
    .es('enlace izquierda/derecha')
    .pt('link esquerda/direita')
    .fr('couplage gauche/droite')
    .it('accoppiamento sinistra/destra')
    .ja('左右リンク')
    .ko('좌/우 링크')
    .zhHans('左右链接')
    .zhHant('左右連結')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='front/back link')
    .es('enlace delante/atrás')
    .pt('link frente/fundo')
    .fr('couplage avant/arrière')
    .it('accoppiamento fronte/retro')
    .ja('前後リンク')
    .ko('전/후 링크')
    .zhHans('前后链接')
    .zhHant('前後連結')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Soft Clip')
    .es('Clip Suave')
    .pt(1)
    .fr(1)
    .it('Clip Lieve')
    .ja('ソフトクリップ')
    .ko('소프트 클립')
    .zhHans('软削峰')
    .zhHant('軟削峰')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='limiter link')
    .es('enlace de limitador')
    .pt('link do limiter')
    .fr('couplage du limiteur')
    .it('accoppiamento limitatore')
    .ja('リミターリンク')
    .ko('리미터 링크')
    .zhHans('限幅器链接')
    .zhHant('限幅器連結')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='saturation side trim')
    .es('ajuste de saturación lateral')
    .pt('volume de saturação dos lados')
    .fr('volume de saturation du side')
    .it('volume saturazione lati')
    .ja('サチュレーションサイドトリム')
    .ko('새츄레이션 사이드 트림')
    .zhHans('饱和侧声道调节')
    .zhHant('飽和側聲道調節')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='LFE')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('低域効果')
    .ko(1)
    .zhHans('低频效果')
    .zhHant('低頻效果')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='amount')
    .es('intensidad')
    .pt('intensidade')
    .fr('intensité')
    .it('quantità')
    .ja('量')
    .ko('정도')
    .zhHans('量')
    .zhHant('量')
    .ar('الكمية')
)

ts.append(T(tag="ParamLabel/text",
    text='trim')
    .es('ajuste')
    .pt('volume')
    .fr('volume')
    .it('vol')
    .ja('トリム')
    .ko('트림')
    .zhHans('调整')
    .zhHant('調整')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Center')
    .es('Centro')
    .pt('Centro')
    .fr('Centre')
    .it('Centro')
    .ja('センター')
    .ko('센터')
    .zhHans('中央')
    .zhHant('中央')
    .ar(0)
)

ts.append(T(tag="ParamLabel/text",
    text='amount')
    .es('intensidad')
    .pt('intensidade')
    .fr('intensité')
    .it('quantità')
    .ja('量')
    .ko('정도')
    .zhHans('量')
    .zhHant('量')
    .ar('الكمية')
)

ts.append(T(tag="ParamLabel/text",
    text='trim')
    .es('ajuste')
    .pt('volume')
    .fr('volume')
    .it('vol')
    .ja('トリム')
    .ko('트림')
    .zhHans('调整')
    .zhHant('調整')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='multichannel only')
    .es('multicanal solamente')
    .pt('multipista somente')
    .fr('multicanal seulement')
    .it('solo multicanale')
    .ja('マルチチャンネルのみ')
    .ko('멀티채널 전용')
    .zhHans('仅限多声道')
    .zhHant('僅限多聲道')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='multichannel only')
    .es('multicanal solamente')
    .pt('multipista somente')
    .fr('multicanal seulement')
    .it('solo multicanale')
    .ja('マルチチャンネルのみ')
    .ko('멀티채널 전용')
    .zhHans('仅限多声道')
    .zhHant('僅限多聲道')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='surround only')
    .es('surround solamente')
    .pt('surround somente')
    .fr('surround seulement')
    .it('solo surround')
    .ja('サラウンドのみ')
    .ko('서라운드 전용')
    .zhHans('仅限环绕声')
    .zhHant('僅限環繞聲')
    .ar(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='surround only')
    .es('surround solamente')
    .pt('surround somente')
    .fr('surround seulement')
    .it('solo surround')
    .ja('サラウンドのみ')
    .ko('서라운드 전용')
    .zhHans('仅限环绕声')
    .zhHant('僅限環繞聲')
    .ar(0)
)

