from pbtranslations.translations import *


ts = TranslationSet()

ts.append(T(tag="Parameter/option",
    context="SidechainSource",
    text='internal')
    .es('interna')
    .pt('interna')
    .fr('interne')
    .it('interna')
    .ja('内部')
    .ko('인터널')
    .zhHans('内部')
    .zhHant('內部')
    .ar('داخلي')
    .he('פנימי')
)

ts.append(T(tag="Parameter/option",
    context="SidechainSource",
    text='external')
    .es('externa')
    .pt('externa')
    .fr('externe')
    .it('esterna')
    .ja('外部')
    .ko('엑스터널')
    .zhHans('外部')
    .zhHant('外部')
    .ar('خارجي')
    .he('חיצוני')
)

ts.append(T(tag="Tagline",
    text='Vulf Compressor Mastering Edition')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Vulf Compressor\nMastering Edition')
    .es(0)
    .pt(0)
    .fr(0)
    .it(0)
    .ja(0)
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Ratio')
    .es('Proporción')
    .pt('Proporção')
    .fr(1)
    .it('Rapporto')
    .ja('比率')
    .ko('비율')
    .zhHans('比率')
    .zhHant('比率')
    .ar('نسبة الضغط')
    .he('יחס')
)

ts.append(T(tag="ClumpLabel/text",
    text='Thresh')
    .es('Umbral')
    .pt('Limite')
    .fr('Seuil')
    .it('Soglia')
    .ja('スレッショルド')
    .ko('기준 레벨')
    .zhHans('阈')
    .zhHant('閾')
    .ar('حد العتبة')
    .he('סף')
)

ts.append(T(tag="ClumpLabel/text",
    text='Makeup')
    .es('Compensación')
    .pt('Compensação')
    .fr('Compensation')
    .it('Compensazione')
    .ja('補償')
    .ko('보상')
    .zhHans('补偿')
    .zhHant('補償')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='comp')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('コンプ')
    .ko('컴프')
    .zhHans('压缩')
    .zhHant('壓縮')
    .ar('الضغط')
    .he('קומפרשן')
)

ts.append(T(tag="Parameter/option",
    text='apply')
    .es('aplicar')
    .pt('aplicar')
    .fr('appliquer')
    .it('applica')
    .ja('適用する')
    .ko('적용')
    .zhHans('应用')
    .zhHant('應用')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Attack')
    .es('Ataque')
    .pt('Ataque')
    .fr('Attaque')
    .it('Attacco')
    .ja('アタック')
    .ko('어택 타임')
    .zhHans('起动时间')
    .zhHant('起動時間')
    .ar('زمن التطبيق')
    .he('זמן-התקף')
)

ts.append(T(tag="ClumpLabel/text",
    text='Release')
    .es('Relajación')
    .pt('Repouso')
    .fr('Retour')
    .it('Rilascio')
    .ja('リリース')
    .ko('릴리즈 타임')
    .zhHans('释放时间')
    .zhHant('釋放時間')
    .ar('التحرير')
    .he('זמן-שחרור')
)

ts.append(T(tag="ClumpLabel/text",
    text='Style')
    .es('Estilo')
    .pt('Estilo')
    .fr(1)
    .it('Stile')
    .ja('スタイル')
    .ko('스타일')
    .zhHans('样式')
    .zhHant('類型')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Dry')
    .es(1)
    .pt(1)
    .fr(1)
    .it('Orig')
    .ja('原音')
    .ko('원음')
    .zhHans('干声')
    .zhHant('乾聲')
    .ar('جاف')
    .he('מיקס')
)

ts.append(T(tag="ClumpLabel/text",
    text='side\nchain')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('サイド\nチェイン')
    .ko('사이드\n체인')
    .zhHans('旁链')
    .zhHant('旁鏈')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Tilt')
    .es('Incl.')
    .pt('Incl.')
    .fr('Incl.')
    .it('Pend.')
    .ja('チルト')
    .ko('틸트')
    .zhHans('倾斜')
    .zhHant('傾斜')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Trim')
    .es('Ajuste')
    .pt('Volume')
    .fr('Volume')
    .it('Vol')
    .ja('トリム')
    .ko('트림')
    .zhHans('调整')
    .zhHant('調整')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='HPF')
    .es('Filtro Paso Altos')
    .pt('Filtro Passa-Altas')
    .fr('Passe-Haut')
    .it('Passa Alto')
    .ja(1)
    .ko(1)
    .zhHans('高通滤波器')
    .zhHant('高通濾波器')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Source')
    .es('Fuente')
    .pt('Fonte')
    .fr(1)
    .it('Sorgente')
    .ja('音源')
    .ko('소스')
    .zhHans('声源')
    .zhHant('聲源')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='soft\nclip')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('ソフト\nクリップ')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="Parameter/option",
    text='brickwall')
    .es(0)
    .pt(0)
    .fr(1)
    .it(0)
    .ja('ブリックウォール')
    .ko(0)
    .zhHans(0)
    .zhHant(0)
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Drive')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja('ドライブ')
    .ko('드라이브')
    .zhHans('输入')
    .zhHant('輸入')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Mix')
    .es('Mezcla')
    .pt(1)
    .fr(1)
    .it('Miscela')
    .ja('ミックス')
    .ko('믹스')
    .zhHans('混合')
    .zhHant('混合')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Trim')
    .es('Ajuste')
    .pt('Volume')
    .fr('Volume')
    .it('Vol')
    .ja('トリム')
    .ko('트림')
    .zhHans('调整')
    .zhHant('調整')
    .ar(0)
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text='Mode')
    .es('Modo')
    .pt('Modo')
    .fr(1)
    .it('Modalità')
    .ja('モード')
    .ko('모드')
    .zhHans('模式')
    .zhHant('模式')
    .ar('الوضع')
    .he('מצב')
)

