from pbt.translations import *


ts = TranslationSet()

ts.append(T(tag="Parameter/option",
    context="TempoSync",
    text='Manual')
    .es(1)
    .pt(1)
    .fr('Manuel')
    .it('Manuale')
    .ja('マニュアル')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('يَدَوِي')
    .he('ידני')
)

ts.append(T(tag="Parameter/option",
    context="TempoSync",
    text='Synced')
    .es('Sincronizado')
    .pt('Sincronizado')
    .fr('Synchronisé')
    .it('Sincronizzato')
    .ja('シンクロ')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('متزامن')
    .he('מסונכרן לטמפו')
)

ts.append(T(tag="Parameter/option",
    context="TremType",
    text='Standard')
    .es('Estándar')
    .pt('Padrão')
    .fr('Normal')
    .it(1)
    .ja('普通')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('عادي')
    .he('סטנדרט')
)

ts.append(T(tag="Parameter/option",
    context="TremType",
    text='Harmonic')
    .es('Armónico')
    .pt('Harmônico')
    .fr('Harmonique')
    .it('Armonico')
    .ja('ハーモニック')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('ايقاعي')
    .he('הרמוני')
)

ts.append(T(tag="Parameter/option",
    context="TremType",
    text='Deep Harmonic')
    .es('Armónico Profundo')
    .pt('Harmônico Profundo')
    .fr('Harmonique Profonde')
    .it('Armoniche Profonde')
    .ja('ディープハーモニック')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('ايقاعي عميق')
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="TremType",
    text='Bass')
    .es('Graves')
    .pt('Graves')
    .fr('Graves')
    .it('Basse')
    .ja('低域')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('الباس')
    .he('בס')
)

ts.append(T(tag="Parameter/option",
    context="TremType",
    text='Treble')
    .es('Agudos')
    .pt('Agudos')
    .fr('Aigus')
    .it('Alte')
    .ja('高域')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('الصوت العالي')
    .he('טרבל')
)

ts.append(T(tag="Parameter/option",
    context="TremType",
    text='Air')
    .es('Aire')
    .pt('Ar')
    .fr(1)
    .it('Aria')
    .ja('エア')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('هواء')
    .he('אוויר')
)

ts.append(T(tag="Parameter/option",
    context="TremType",
    text='Mid/Side')
    .es(1)
    .pt(1)
    .fr(1)
    .it('Centro/Lati')
    .ja('ミッド/サイド')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('ميد/سايد')
    .he('אמצע/צד')
)

ts.append(T(tag="Parameter/option",
    context="TremType",
    text='Mid Only')
    .es('Solo Mid')
    .pt('Solo: Meio')
    .fr('Mid Seulement')
    .it('Solo Centro')
    .ja('ミッドのみ')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('الميد فقط')
    .he('רק אמצע')
)

ts.append(T(tag="Parameter/option",
    context="TremType",
    text='Side Only')
    .es('Solo Side')
    .pt('Solo: Lados')
    .fr('Side Seulement')
    .it('Solo Lati')
    .ja('サイドのみ')
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar('السايد فقط')
    .he('רק צד')
)

ts.append(T(tag="Tagline",
    text='Classic tremolo for the 21st century')
    .es('Trémolo clásico para el siglo XXI')
    .pt('Tremolo clássico, adaptado ao século XXI')
    .fr('Trémolo classique pour le 21ème siècle')
    .it('Tremolo classico per il XXI secolo')
    .ja('繋ぎ目のない波の輪廻\u300021世紀のためのクラシックトレモロ')
    .ko('21세기를 위한 클래식 트레몰로')
    .zhHans('21世纪的经典颤音')
    .zhHant('21世紀的經典顫音')
    .ar('ارتعاش كلاسيكي للقرن الحادي والعشرين')
    .he('טרמולו קלאסי למאה ה-21')
)

ts.append(T(tag="ClumpLabel/text",
    text='RATE')
    .es('VELOCIDAD')
    .pt('FREQUÊNCIA')
    .fr('VITESSE')
    .it('FREQUENZA')
    .ja('レート')
    .ko('속도/비율')
    .zhHans('速度/比率')
    .zhHant('速度/比率')
    .ar('المعدل')
    .he('תדירות')
)

ts.append(T(tag="ParamLabel/text",
    text='BPM')
    .es(1)
    .pt(1)
    .fr(1)
    .it(1)
    .ja(1)
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar(1)
    .he(1)
)

ts.append(T(tag="ParamLabel/text",
    text='BPM Sync')
    .es('Sincronizar BPM')
    .pt('Sincronizar BPM')
    .fr('Synchronisation BPM')
    .it('Sinc BPM')
    .ja('BPMシンク')
    .ko('BPM 싱크')
    .zhHans('BPM同步')
    .zhHant('BPM同步')
    .ar('BPMتزامن ال')
    .he('BPM סינק')
)

ts.append(T(tag="ParamLabel/text",
    text='Rate')
    .es('Velocidad')
    .pt('Frequência')
    .fr('Fréquence')
    .it('Frequenza')
    .ja('レート')
    .ko('속도/비율')
    .zhHans('比率')
    .zhHant('比率')
    .ar('المعدل')
    .he('תדירות')
)

ts.append(T(tag="ParamLabel/text",
    text='Multiplier')
    .es('Multiplicador')
    .pt('Multiplicador')
    .fr('Multiplicateur')
    .it('Moltiplicatore')
    .ja('倍率')
    .ko('비율 변경')
    .zhHans('乘数')
    .zhHant('乘數')
    .ar('معامل الضرب')
    .he('מכפיל')
)

ts.append(T(tag="ClumpLabel/text",
    text='SHAPE')
    .es('FORMA')
    .pt('FORMATO')
    .fr('FORME')
    .it('FORMA')
    .ja('シェイプ')
    .ko('트레몰로 방식')
    .zhHans('形状')
    .zhHant('形狀')
    .ar('الشكل')
    .he('צורה')
)

ts.append(T(tag="ParamLabel/text",
    text='Depth')
    .es('Profundidad')
    .pt('Profundidade')
    .fr('Amplitude')
    .it('Profondità')
    .ja('深度')
    .ko('깊이')
    .zhHans('深度')
    .zhHant('深度')
    .ar('العمق')
    .he('עומק')
)

ts.append(T(tag="ParamLabel/text",
    text='Wave')
    .es('Onda')
    .pt('Onda')
    .fr('Onde')
    .it('Onda')
    .ja('波形')
    .ko('웨이브')
    .zhHans('波形')
    .zhHant('波形')
    .ar('الموجة')
    .he('גל')
)

ts.append(T(tag="ParamLabel/text",
    text='Bias')
    .es(1)
    .pt('Inclinação')
    .fr('Tension')
    .it(1)
    .ja('バイアス')
    .ko('바이어스')
    .zhHans('交流偏磁')
    .zhHant('交流偏磁')
    .ar('الانحياز')
    .he('הטייה')
)

ts.append(T(tag="ParamLabel/text",
    text='Symmetry')
    .es('Simetría')
    .pt('Simetria')
    .fr('Symétrie')
    .it('Simmetria')
    .ja('対称性')
    .ko('대칭')
    .zhHans('对称')
    .zhHant('對稱')
    .ar('التماثل')
    .he('סימטריה')
)

ts.append(T(tag="ClumpLabel/text",
    text='VIBE')
    .es('VIBRA')
    .pt(1)
    .fr('AMBIANCE')
    .it(1)
    .ja('バイブ')
    .ko('바이브')
    .zhHans('氛围')
    .zhHant('氛圍')
    .ar('الجو')
    .he('וייב')
)

ts.append(T(tag="ParamLabel/text",
    text='Tube Color')
    .es('Coloración')
    .pt('Coloração')
    .fr('Coloration')
    .it('Sat Valvolare')
    .ja('チューブカラー')
    .ko('진공관 색채')
    .zhHans('真空管染色')
    .zhHant('真空管染色')
    .ar('لون الأنبوب')
    .he('צבע מנורות')
)

ts.append(T(tag="ParamLabel/text",
    text='Trem Type')
    .es('Tipo de Trémolo')
    .pt('Tipo de Tremolo')
    .fr('Type de Trémolo')
    .it('Tipo Tremolo')
    .ja('トレムタイプ')
    .ko('트렘 방식')
    .zhHans('颤音类型')
    .zhHant('顫音類型')
    .ar('نوع الارتعاش')
    .he('סוג טרמולו')
)

ts.append(T(tag="ClumpLabel/text",
    text='ADV SHAPE')
    .es('FORMA EXT')
    .pt('FORMATO +')
    .fr('FORME EXT')
    .it('FORMA AVZ')
    .ja('シェイプ微調整')
    .ko('세부 형식 설정')
    .zhHans('高级形状调节')
    .zhHant('進階型狀調節')
    .ar('+الشكل')
    .he('צורה ועוד')
)

ts.append(T(tag="ParamLabel/text",
    text='Phase Offset')
    .es('Desfase')
    .pt('Deslocamento de Fase')
    .fr('Déphasage')
    .it('Sfasamento')
    .ja('フェーズオフセット')
    .ko('페이즈 오프셋')
    .zhHans('相位偏移')
    .zhHant('相位偏移')
    .ar('فرق الطور')
    .he('פאזה אוף-סט')
)

ts.append(T(tag="ParamLabel/text",
    text='Stereo Phase')
    .es('Fase Estéreo')
    .pt('Fase – Estéreo')
    .fr('Phase Stéréo')
    .it('Fase Stereo')
    .ja('ステレオフェーズ')
    .ko('스테레오 페이즈')
    .zhHans('立体声相位')
    .zhHant('立體聲相位')
    .ar('طور إستريو')
    .he('פאזה סטריאופונית')
)

ts.append(T(tag="ClumpLabel/text",
    text='MISC')
    .es(1)
    .pt('OUTROS')
    .fr('AUTRES')
    .it(1)
    .ja('その他')
    .ko('기타')
    .zhHans('杂项')
    .zhHant('雜項')
    .ar('متنوعات')
    .he('שונות')
)

ts.append(T(tag="ParamLabel/text",
    text='Trem Volume\nComp')
    .es('Compensar Volumen\nde Trémolo')
    .pt('Compensar Volume\ndo Tremolo')
    .fr('Compensation de\nVolume du Trémolo')
    .it('Compensazione\nVolume Tremolo')
    .ja('ボリューム\n補償')
    .ko('트렘 볼륨\n보상')
    .zhHans('颤音音量\n补偿')
    .zhHant('顫音音量\n補償')
    .ar('الإرتعاش\nتعويض علو صوت')
    .he('פיצוי ווליום טרמולו')
)

ts.append(T(tag="ParamLabel/text",
    text='Tube Noise\nGain')
    .es('Ruido\nde Bulbos')
    .pt('Ganho do Ruído\nda Válvula')
    .fr('Gain de\nBruit du Tube')
    .it('Volume Rumore\nValvole')
    .ja('チューブ\nノイズゲイン')
    .ko('진공관 노이즈 게인')
    .zhHans('真空管\n噪声')
    .zhHant('真空管\n噪聲')
    .ar('الانبوب\nربح ضجيج')
    .he('רעש מנורות')
)

ts.append(T(tag="ClumpLabel/text",
    text='ADV RATE')
    .es('VELOCIDAD EXT')
    .pt('FREQUÊNCIA +')
    .fr('VITESSE EXT')
    .it('TIMING AVZ')
    .ja('レート微調整')
    .ko('세부 속도 조절')
    .zhHans('高级速度调节')
    .zhHant('進階速度調節')
    .ar('+المعدل')
    .he('תדירות ועוד')
)

ts.append(T(tag="ParamLabel/text",
    text='Swing')
    .es(1)
    .pt('Suingue')
    .fr(1)
    .it(1)
    .ja('スイング')
    .ko('스윙')
    .zhHans('摇摆')
    .zhHant('搖擺')
    .ar('الإيقاع')
    .he('סווינג')
)

ts.append(T(tag="ClumpLabel/text",
    text='TRIM')
    .es('AJUSTE')
    .pt('VOLUME')
    .fr('VOLUME')
    .it('VOL')
    .ja('トリム')
    .ko('트림')
    .zhHans('调整')
    .zhHant('調整')
    .ar('المُوازَنةٌ')
    .he('טרים')
)

ts.append(T(tag="ParamLabel/text",
    text='Input')
    .es('Entrada')
    .pt('Entrada')
    .fr('Entrée')
    .it('Ingresso')
    .ja('インプット')
    .ko('인풋')
    .zhHans('输入')
    .zhHant('輸入')
    .ar('إشارة الإدخال')
    .he('כניסה')
)

ts.append(T(tag="ParamLabel/text",
    text='Output')
    .es('Salida')
    .pt('Saída')
    .fr('Sortie')
    .it('Uscita')
    .ja('アウトプット')
    .ko('아웃풋')
    .zhHans('输出')
    .zhHant('輸出')
    .ar('إشارة الإخراج')
    .he('יציאה')
)

