from pbt.translations import *


ts = TranslationSet()

ts.append(T(tag="ClumpLabel/text",
    text="BASS")
    .es("BAJOS")
    .pt("GRAVE")
    .fr("GRAVES")
    .ja("低域")
    .ko("저역 컨트롤")
    .zhHans("低频")
    .zhHant("低頻")
    .ar("باَس")
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text="EQ STYLE")
    .es("ESTILO DE EQ")
    .pt("Estilo de EQ")
    .fr("STYLE DE EQ")
    .ja("EQスタイル")
    .ko("EQ 스타일")
    .zhHans("EQ样式")
    .zhHant("EQ類型")
    .ar("EQ اسلوب ال")
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text="HIGH CUT")
    .es("PASA ALTOS")
    .pt("CORTE AGUDO")
    .fr("COUPE-HAUT")
    .ja("ハイカット")
    .ko("하이컷 필터")
    .zhHans("高切")
    .zhHant("高切")
    .ar("تمرير منخفض")
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text="LOW CUT")
    .es("PASA BAJOS")
    .pt("CORTE GRAVE")
    .fr("COUPE-BAS")
    .ja("ローカット")
    .ko("로우컷 필터")
    .zhHans("低切")
    .zhHant("低切")
    .ar("تمرير عال")
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text="MASTER")
    .es("MÁSTER")
    .pt(1)
    .fr(1)
    .ja("マスター")
    .ko("마스터")
    .zhHans("主控")
    .zhHant("主控")
    .ar("الماستر")
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text="MODE")
    .es("MODO")
    .pt("MODO")
    .fr(1)
    .ja("モード")
    .ko("세부 조절")
    .zhHans("高级模式")
    .zhHant("進階模式")
    .ar("الوضع ")
    .he(0)
)

ts.append(T(tag="ClumpLabel/text",
    text="TREBLE")
    .es("ALTOS")
    .pt("AGUDO")
    .fr("AIGUS")
    .ja("高域")
    .ko("고역 컨트롤")
    .zhHans("高频")
    .zhHant("高頻")
    .ar("الصوت العالي")
    .he(0)
)

ts.append(T(tag="HUD/state",
    text="Left")
    .es("Izquierdo")
    .pt("Esquerda")
    .fr("Gauche")
    .ja("左のみ")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("اليسار")
    .he(0)
)

ts.append(T(tag="HUD/state",
    text="Mid")
    .es(1)
    .pt("Meio")
    .fr(1)
    .ja("ミッド")
    .ko("미드")
    .zhHans("中")
    .zhHant("中")
    .ar("الميد")
    .he(0)
)

ts.append(T(tag="HUD/state",
    text="Right")
    .es("Derecho")
    .pt("Direita")
    .fr("Droite")
    .ja("右のみ")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("اليمين")
    .he(0)
)

ts.append(T(tag="HUD/state",
    text="Side")
    .es(1)
    .pt("Lados")
    .fr(1)
    .ja("サイド")
    .ko("사이드")
    .zhHans("侧")
    .zhHant("側")
    .ar("السايد")
    .he(0)
)

ts.append(T(tag="HUD/state",
    text="Stereo")
    .es("Estéreo")
    .pt("Estéreo")
    .fr("Stéréo")
    .ja("ステレオ")
    .ko("스테레오")
    .zhHans("立体声")
    .zhHant("立體聲")
    .ar("إستريو")
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text="Air")
    .es("Aire")
    .pt("Ar")
    .fr(1)
    .ja("エア")
    .ko("에어")
    .zhHans("空气感")
    .zhHant("空氣感")
    .ar("هواء")
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text="Freq")
    .es("Frecuencia")
    .pt(1)
    .fr("Fréq")
    .ja("周波数")
    .ko("프리퀀시")
    .zhHans("频率")
    .zhHant("頻率")
    .ar("التردد")
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text="Frequency")
    .es("Frecuencia")
    .pt("Frequência")
    .fr("Fréquence")
    .ja("基準周波数")
    .ko("기준 프리퀀시")
    .zhHans("频率")
    .zhHant("頻率")
    .ar("التردد")
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text="Gain")
    .es("Ganancia")
    .pt("Ganho")
    .fr(1)
    .ja("ゲイン")
    .ko("게인")
    .zhHans("增益")
    .zhHant("增益")
    .ar("الربح ")
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text="Linear Phase")
    .es("Fase linear")
    .pt("Fase Linear")
    .fr("Phase Linéaire")
    .ja("リニアフェーズ")
    .ko("리니어 페이즈")
    .zhHans("线性相位")
    .zhHant("線性相位")
    .ar("طورُخطي")
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text="Mix")
    .es("Mezcla")
    .pt(1)
    .fr(1)
    .ja("ミックス")
    .ko("믹스")
    .zhHans("混合")
    .zhHant("混合")
    .ar("الميكس")
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text="Processing Mode")
    .es("Modo de procesamiento")
    .pt("Modo de Processamento")
    .fr("Mode de Traitement")
    .ja("動作モード")
    .ko("프로세스 모드")
    .zhHans("处理模式")
    .zhHant("處理模式")
    .ar("وضع المعالجة")
    .he(0)
)

ts.append(T(tag="ParamLabel/text",
    text="Slope")
    .es("Pendiente")
    .pt("Declive")
    .fr("Ordre")
    .ja("スロープ")
    .ko("기울기")
    .zhHans("坡度")
    .zhHant("坡度")
    .ar("الميل")
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="ProcessingMode",
    text="Left Only")
    .es("Solo izquierdo")
    .pt("Solo: Esquerda")
    .fr("Gauche Seulement")
    .ja("左のみ")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("اليسار فقط")
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="ProcessingMode",
    text="Mid Only")
    .es("Solo Mid")
    .pt("Solo: Meio")
    .fr("Mid Seulement")
    .ja("ミッドのみ")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("الميد فقط ")
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="ProcessingMode",
    text="Right Only")
    .es("Solo derecho")
    .pt("Solo: Direita")
    .fr("Droite Seulement")
    .ja("右のみ")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("اليمين فقط")
    .he(0)
)

ts.append(T(tag="Parameter/option",
    context="ProcessingMode",
    text="Stereo")
    .es("Estéreo")
    .pt("Estéreo")
    .fr("Stéréo")
    .ja("ステレオ")
    .ko(1)
    .zhHans(1)
    .zhHant(1)
    .ar("إستريو")
    .he(0)
)

ts.append(T(tag="Tagline",
    text="Timeless EQ, taken back to the future.")
    .es("Ecualización clásica, de vuelta al futuro.")
    .pt("Equalização clássica, trazida de volta ao futuro.")
    .fr("Égaliseur classique, de retour vers le futur.")
    .ja("音の輪郭、枠線を微細にコントロール　Mix and Mastering Equalizer")
    .ko("사운드의 윤곽을 만들어내는 직관적인 EQ")
    .zhHans("绝美永恒的音色，带你穿越未来")
    .zhHant("絕美永恆的音色，帶你穿越未來")
    .ar("موازن ترددات خالد، مبعوث إلَى المستقبل من جديد")
    .he(0)
)

